// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/String.h>
String String_toUpperCase(String);
String String_toLowerCase(String);
String String_charAt(String,int);
vdynamic* String_charCodeAt(String,int);
int String_findChar(String,int,int,vbyte*,int);
int String_indexOf(String,String,vdynamic*);
int String_lastIndexOf(String,String,vdynamic*);
#include <hl/types/ArrayObj.h>
hl__types__ArrayObj String_split(String,String);
String String_substr(String,int,vdynamic*);
String String_substring(String,int,vdynamic*);
String String_toString(String);
vbyte* String_toUtf8(String);
vbyte* String___string(String);
int String___compare(String,vdynamic*);
#include <hl/BaseType.h>
bool hl_BaseType_check(hl__BaseType,vdynamic*);
String String_fromCharCode(int);
String String___alloc__(vbyte*,int);
vbyte* String_call_toString(vdynamic*);
String String_fromUCS2(vbyte*);
String String_fromUTF8(vbyte*);
String String___add__(String,String);
void String_new(String,String);
#include <hl/natives.h>
#include <_std/Date.h>
void Date_new(Date,int,int,int,int,int,int);
String Date_toString(Date);
vbyte* Date___string(Date);
void HlcTestSuite_assert(bool,String);
void HlcTestSuite_testBasicTypes(void);
void HlcTestSuite_testArrays(void);
void HlcTestSuite_testMaps(void);
void HlcTestSuite_testStrings(void);
void HlcTestSuite_testMath(void);
void HlcTestSuite_testClasses(void);
void HlcTestSuite_testStaticMembers(void);
void HlcTestSuite_testEnums(void);
void HlcTestSuite_testExceptions(void);
void HlcTestSuite_main(void);
#include <hl/types/ArrayAccess.h>
vdynamic* hl_types_ArrayAccess_getDyn(hl__types__ArrayAccess,int);
void hl_types_ArrayAccess_setDyn(hl__types__ArrayAccess,int,vdynamic*);
void hl_types_ArrayAccess_blit(hl__types__ArrayAccess,int,hl__types__ArrayAccess,int,int);
#include <hl/types/ArrayDyn.h>
int hl_types_ArrayDyn_get_length(hl__types__ArrayDyn);
vdynamic* hl_types_ArrayDyn_getDyn(hl__types__ArrayDyn,int);
void hl_types_ArrayDyn_setDyn(hl__types__ArrayDyn,int,vdynamic*);
void hl_types_ArrayDyn_blit(hl__types__ArrayDyn,int,hl__types__ArrayAccess,int,int);
hl__types__ArrayDyn hl_types_ArrayDyn_concat(hl__types__ArrayDyn,hl__types__ArrayDyn);
String hl_types_ArrayDyn_join(hl__types__ArrayDyn,String);
vdynamic* hl_types_ArrayDyn_pop(hl__types__ArrayDyn);
int hl_types_ArrayDyn_push(hl__types__ArrayDyn,vdynamic*);
void hl_types_ArrayDyn_reverse(hl__types__ArrayDyn);
void hl_types_ArrayDyn_resize(hl__types__ArrayDyn,int);
vdynamic* hl_types_ArrayDyn_shift(hl__types__ArrayDyn);
hl__types__ArrayDyn hl_types_ArrayDyn_slice(hl__types__ArrayDyn,int,vdynamic*);
void hl_types_ArrayDyn_sort(hl__types__ArrayDyn,vclosure*);
hl__types__ArrayDyn hl_types_ArrayDyn_splice(hl__types__ArrayDyn,int,int);
String hl_types_ArrayDyn_toString(hl__types__ArrayDyn);
void hl_types_ArrayDyn_unshift(hl__types__ArrayDyn,vdynamic*);
void hl_types_ArrayDyn_insert(hl__types__ArrayDyn,int,vdynamic*);
bool hl_types_ArrayDyn_contains(hl__types__ArrayDyn,vdynamic*);
bool hl_types_ArrayDyn_remove(hl__types__ArrayDyn,vdynamic*);
int hl_types_ArrayDyn_indexOf(hl__types__ArrayDyn,vdynamic*,vdynamic*);
int hl_types_ArrayDyn_lastIndexOf(hl__types__ArrayDyn,vdynamic*,vdynamic*);
hl__types__ArrayDyn hl_types_ArrayDyn_copy(hl__types__ArrayDyn);
#include <haxe/iterators/ArrayIterator.h>
haxe__iterators__ArrayIterator hl_types_ArrayDyn_iterator(hl__types__ArrayDyn);
#include <haxe/iterators/ArrayKeyValueIterator.h>
haxe__iterators__ArrayKeyValueIterator hl_types_ArrayDyn_keyValueIterator(hl__types__ArrayDyn);
hl__types__ArrayDyn hl_types_ArrayDyn_map(hl__types__ArrayDyn,vclosure*);
hl__types__ArrayDyn hl_types_ArrayDyn_filter(hl__types__ArrayDyn,vclosure*);
vdynamic* hl_types_ArrayDyn___get_field(hl__types__ArrayDyn,int);
vdynamic* hl_types_ArrayDyn___cast(hl__types__ArrayDyn,hl_type*);
int hl_types_ArrayDyn___compare(hl__types__ArrayDyn,vdynamic*);
vbyte* hl_types_ArrayDyn___string(hl__types__ArrayDyn);
#include <hl/types/ArrayBase.h>
int hl_types_ArrayBase_pushDyn(hl__types__ArrayBase,vdynamic*);
vdynamic* hl_types_ArrayBase_popDyn(hl__types__ArrayBase);
vdynamic* hl_types_ArrayBase_shiftDyn(hl__types__ArrayBase);
void hl_types_ArrayBase_unshiftDyn(hl__types__ArrayBase,vdynamic*);
void hl_types_ArrayBase_insertDyn(hl__types__ArrayBase,int,vdynamic*);
bool hl_types_ArrayBase_containsDyn(hl__types__ArrayBase,vdynamic*);
bool hl_types_ArrayBase_removeDyn(hl__types__ArrayBase,vdynamic*);
void hl_types_ArrayBase_sortDyn(hl__types__ArrayBase,vclosure*);
hl__types__ArrayBase hl_types_ArrayBase_slice(hl__types__ArrayBase,int,vdynamic*);
hl__types__ArrayBase hl_types_ArrayBase_splice(hl__types__ArrayBase,int,int);
String hl_types_ArrayBase_join(hl__types__ArrayBase,String);
void hl_types_ArrayBase_reverse(hl__types__ArrayBase);
void hl_types_ArrayBase_resize(hl__types__ArrayBase,int);
String hl_types_ArrayBase_toString(hl__types__ArrayBase);
vdynamic* hl_types_ArrayBase___cast(hl__types__ArrayBase,hl_type*);
bool hl_types_ArrayBase_isArrayObj(hl__types__ArrayBase);
vbyte* hl_types_ArrayBase___string(hl__types__ArrayBase);
#include <hl/types/ArrayBytes_Int.h>
hl__types__ArrayBytes_Int hl_types_ArrayBase_allocI32(vbyte*,int);
#include <hl/types/ArrayBytes_hl_UI16.h>
hl__types__ArrayBytes_hl_UI16 hl_types_ArrayBase_allocUI16(vbyte*,int);
#include <hl/types/ArrayBytes_hl_F32.h>
hl__types__ArrayBytes_hl_F32 hl_types_ArrayBase_allocF32(vbyte*,int);
#include <hl/types/ArrayBytes_Float.h>
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
hl__types__ArrayBytes_Float hl_types_ArrayBytes_Float_concat(hl__types__ArrayBytes_Float,hl__types__ArrayBytes_Float);
String hl_types_ArrayBytes_Float_join(hl__types__ArrayBytes_Float,String);
vdynamic* hl_types_ArrayBytes_Float_pop(hl__types__ArrayBytes_Float);
int hl_types_ArrayBytes_Float_push(hl__types__ArrayBytes_Float,double);
void hl_types_ArrayBytes_Float_reverse(hl__types__ArrayBytes_Float);
vdynamic* hl_types_ArrayBytes_Float_shift(hl__types__ArrayBytes_Float);
void hl_types_ArrayBytes_Float_blit(hl__types__ArrayBytes_Float,int,hl__types__ArrayAccess,int,int);
hl__types__ArrayBase hl_types_ArrayBytes_Float_slice(hl__types__ArrayBytes_Float,int,vdynamic*);
void hl_types_ArrayBytes_Float_sort(hl__types__ArrayBytes_Float,vclosure*);
hl__types__ArrayBase hl_types_ArrayBytes_Float_splice(hl__types__ArrayBytes_Float,int,int);
String hl_types_ArrayBytes_Float_toString(hl__types__ArrayBytes_Float);
void hl_types_ArrayBytes_Float_unshift(hl__types__ArrayBytes_Float,double);
void hl_types_ArrayBytes_Float_insert(hl__types__ArrayBytes_Float,int,double);
bool hl_types_ArrayBytes_Float_contains(hl__types__ArrayBytes_Float,double);
bool hl_types_ArrayBytes_Float_remove(hl__types__ArrayBytes_Float,double);
int hl_types_ArrayBytes_Float_indexOf(hl__types__ArrayBytes_Float,double,vdynamic*);
int hl_types_ArrayBytes_Float_lastIndexOf(hl__types__ArrayBytes_Float,double,vdynamic*);
hl__types__ArrayBytes_Float hl_types_ArrayBytes_Float_copy(hl__types__ArrayBytes_Float);
haxe__iterators__ArrayIterator hl_types_ArrayBytes_Float_iterator(hl__types__ArrayBytes_Float);
haxe__iterators__ArrayKeyValueIterator hl_types_ArrayBytes_Float_keyValueIterator(hl__types__ArrayBytes_Float);
hl__types__ArrayDyn hl_types_ArrayBytes_Float_map(hl__types__ArrayBytes_Float,vclosure*);
hl__types__ArrayBytes_Float hl_types_ArrayBytes_Float_filter(hl__types__ArrayBytes_Float,vclosure*);
void hl_types_ArrayBytes_Float_resize(hl__types__ArrayBytes_Float,int);
vdynamic* hl_types_ArrayBytes_Float_getDyn(hl__types__ArrayBytes_Float,int);
void hl_types_ArrayBytes_Float_setDyn(hl__types__ArrayBytes_Float,int,vdynamic*);
int hl_types_ArrayBytes_Float_pushDyn(hl__types__ArrayBytes_Float,vdynamic*);
vdynamic* hl_types_ArrayBytes_Float_popDyn(hl__types__ArrayBytes_Float);
vdynamic* hl_types_ArrayBytes_Float_shiftDyn(hl__types__ArrayBytes_Float);
void hl_types_ArrayBytes_Float_unshiftDyn(hl__types__ArrayBytes_Float,vdynamic*);
void hl_types_ArrayBytes_Float_insertDyn(hl__types__ArrayBytes_Float,int,vdynamic*);
bool hl_types_ArrayBytes_Float_containsDyn(hl__types__ArrayBytes_Float,vdynamic*);
bool hl_types_ArrayBytes_Float_removeDyn(hl__types__ArrayBytes_Float,vdynamic*);
void hl_types_ArrayBytes_Float_sortDyn(hl__types__ArrayBytes_Float,vclosure*);
void hl_types_ArrayBytes_Float___expand(hl__types__ArrayBytes_Float,int);
hl__types__ArrayBytes_hl_F32 hl_types_ArrayBytes_hl_F32_concat(hl__types__ArrayBytes_hl_F32,hl__types__ArrayBytes_hl_F32);
String hl_types_ArrayBytes_hl_F32_join(hl__types__ArrayBytes_hl_F32,String);
vdynamic* hl_types_ArrayBytes_hl_F32_pop(hl__types__ArrayBytes_hl_F32);
int hl_types_ArrayBytes_hl_F32_push(hl__types__ArrayBytes_hl_F32,float);
void hl_types_ArrayBytes_hl_F32_reverse(hl__types__ArrayBytes_hl_F32);
vdynamic* hl_types_ArrayBytes_hl_F32_shift(hl__types__ArrayBytes_hl_F32);
void hl_types_ArrayBytes_hl_F32_blit(hl__types__ArrayBytes_hl_F32,int,hl__types__ArrayAccess,int,int);
hl__types__ArrayBase hl_types_ArrayBytes_hl_F32_slice(hl__types__ArrayBytes_hl_F32,int,vdynamic*);
void hl_types_ArrayBytes_hl_F32_sort(hl__types__ArrayBytes_hl_F32,vclosure*);
hl__types__ArrayBase hl_types_ArrayBytes_hl_F32_splice(hl__types__ArrayBytes_hl_F32,int,int);
String hl_types_ArrayBytes_hl_F32_toString(hl__types__ArrayBytes_hl_F32);
void hl_types_ArrayBytes_hl_F32_unshift(hl__types__ArrayBytes_hl_F32,float);
void hl_types_ArrayBytes_hl_F32_insert(hl__types__ArrayBytes_hl_F32,int,float);
bool hl_types_ArrayBytes_hl_F32_contains(hl__types__ArrayBytes_hl_F32,float);
bool hl_types_ArrayBytes_hl_F32_remove(hl__types__ArrayBytes_hl_F32,float);
int hl_types_ArrayBytes_hl_F32_indexOf(hl__types__ArrayBytes_hl_F32,float,vdynamic*);
int hl_types_ArrayBytes_hl_F32_lastIndexOf(hl__types__ArrayBytes_hl_F32,float,vdynamic*);
hl__types__ArrayBytes_hl_F32 hl_types_ArrayBytes_hl_F32_copy(hl__types__ArrayBytes_hl_F32);
haxe__iterators__ArrayIterator hl_types_ArrayBytes_hl_F32_iterator(hl__types__ArrayBytes_hl_F32);
haxe__iterators__ArrayKeyValueIterator hl_types_ArrayBytes_hl_F32_keyValueIterator(hl__types__ArrayBytes_hl_F32);
hl__types__ArrayDyn hl_types_ArrayBytes_hl_F32_map(hl__types__ArrayBytes_hl_F32,vclosure*);
hl__types__ArrayBytes_hl_F32 hl_types_ArrayBytes_hl_F32_filter(hl__types__ArrayBytes_hl_F32,vclosure*);
void hl_types_ArrayBytes_hl_F32_resize(hl__types__ArrayBytes_hl_F32,int);
vdynamic* hl_types_ArrayBytes_hl_F32_getDyn(hl__types__ArrayBytes_hl_F32,int);
void hl_types_ArrayBytes_hl_F32_setDyn(hl__types__ArrayBytes_hl_F32,int,vdynamic*);
int hl_types_ArrayBytes_hl_F32_pushDyn(hl__types__ArrayBytes_hl_F32,vdynamic*);
vdynamic* hl_types_ArrayBytes_hl_F32_popDyn(hl__types__ArrayBytes_hl_F32);
vdynamic* hl_types_ArrayBytes_hl_F32_shiftDyn(hl__types__ArrayBytes_hl_F32);
void hl_types_ArrayBytes_hl_F32_unshiftDyn(hl__types__ArrayBytes_hl_F32,vdynamic*);
void hl_types_ArrayBytes_hl_F32_insertDyn(hl__types__ArrayBytes_hl_F32,int,vdynamic*);
bool hl_types_ArrayBytes_hl_F32_containsDyn(hl__types__ArrayBytes_hl_F32,vdynamic*);
bool hl_types_ArrayBytes_hl_F32_removeDyn(hl__types__ArrayBytes_hl_F32,vdynamic*);
void hl_types_ArrayBytes_hl_F32_sortDyn(hl__types__ArrayBytes_hl_F32,vclosure*);
void hl_types_ArrayBytes_hl_F32___expand(hl__types__ArrayBytes_hl_F32,int);
hl__types__ArrayBytes_hl_UI16 hl_types_ArrayBytes_hl_UI16_concat(hl__types__ArrayBytes_hl_UI16,hl__types__ArrayBytes_hl_UI16);
String hl_types_ArrayBytes_hl_UI16_join(hl__types__ArrayBytes_hl_UI16,String);
vdynamic* hl_types_ArrayBytes_hl_UI16_pop(hl__types__ArrayBytes_hl_UI16);
int hl_types_ArrayBytes_hl_UI16_push(hl__types__ArrayBytes_hl_UI16,unsigned short);
void hl_types_ArrayBytes_hl_UI16_reverse(hl__types__ArrayBytes_hl_UI16);
vdynamic* hl_types_ArrayBytes_hl_UI16_shift(hl__types__ArrayBytes_hl_UI16);
void hl_types_ArrayBytes_hl_UI16_blit(hl__types__ArrayBytes_hl_UI16,int,hl__types__ArrayAccess,int,int);
hl__types__ArrayBase hl_types_ArrayBytes_hl_UI16_slice(hl__types__ArrayBytes_hl_UI16,int,vdynamic*);
void hl_types_ArrayBytes_hl_UI16_sort(hl__types__ArrayBytes_hl_UI16,vclosure*);
hl__types__ArrayBase hl_types_ArrayBytes_hl_UI16_splice(hl__types__ArrayBytes_hl_UI16,int,int);
String hl_types_ArrayBytes_hl_UI16_toString(hl__types__ArrayBytes_hl_UI16);
void hl_types_ArrayBytes_hl_UI16_unshift(hl__types__ArrayBytes_hl_UI16,unsigned short);
void hl_types_ArrayBytes_hl_UI16_insert(hl__types__ArrayBytes_hl_UI16,int,unsigned short);
bool hl_types_ArrayBytes_hl_UI16_contains(hl__types__ArrayBytes_hl_UI16,unsigned short);
bool hl_types_ArrayBytes_hl_UI16_remove(hl__types__ArrayBytes_hl_UI16,unsigned short);
int hl_types_ArrayBytes_hl_UI16_indexOf(hl__types__ArrayBytes_hl_UI16,unsigned short,vdynamic*);
int hl_types_ArrayBytes_hl_UI16_lastIndexOf(hl__types__ArrayBytes_hl_UI16,unsigned short,vdynamic*);
hl__types__ArrayBytes_hl_UI16 hl_types_ArrayBytes_hl_UI16_copy(hl__types__ArrayBytes_hl_UI16);
haxe__iterators__ArrayIterator hl_types_ArrayBytes_hl_UI16_iterator(hl__types__ArrayBytes_hl_UI16);
haxe__iterators__ArrayKeyValueIterator hl_types_ArrayBytes_hl_UI16_keyValueIterator(hl__types__ArrayBytes_hl_UI16);
hl__types__ArrayDyn hl_types_ArrayBytes_hl_UI16_map(hl__types__ArrayBytes_hl_UI16,vclosure*);
hl__types__ArrayBytes_hl_UI16 hl_types_ArrayBytes_hl_UI16_filter(hl__types__ArrayBytes_hl_UI16,vclosure*);
void hl_types_ArrayBytes_hl_UI16_resize(hl__types__ArrayBytes_hl_UI16,int);
vdynamic* hl_types_ArrayBytes_hl_UI16_getDyn(hl__types__ArrayBytes_hl_UI16,int);
void hl_types_ArrayBytes_hl_UI16_setDyn(hl__types__ArrayBytes_hl_UI16,int,vdynamic*);
int hl_types_ArrayBytes_hl_UI16_pushDyn(hl__types__ArrayBytes_hl_UI16,vdynamic*);
vdynamic* hl_types_ArrayBytes_hl_UI16_popDyn(hl__types__ArrayBytes_hl_UI16);
vdynamic* hl_types_ArrayBytes_hl_UI16_shiftDyn(hl__types__ArrayBytes_hl_UI16);
void hl_types_ArrayBytes_hl_UI16_unshiftDyn(hl__types__ArrayBytes_hl_UI16,vdynamic*);
void hl_types_ArrayBytes_hl_UI16_insertDyn(hl__types__ArrayBytes_hl_UI16,int,vdynamic*);
bool hl_types_ArrayBytes_hl_UI16_containsDyn(hl__types__ArrayBytes_hl_UI16,vdynamic*);
bool hl_types_ArrayBytes_hl_UI16_removeDyn(hl__types__ArrayBytes_hl_UI16,vdynamic*);
void hl_types_ArrayBytes_hl_UI16_sortDyn(hl__types__ArrayBytes_hl_UI16,vclosure*);
void hl_types_ArrayBytes_hl_UI16___expand(hl__types__ArrayBytes_hl_UI16,int);
hl__types__ArrayBytes_Int hl_types_ArrayBytes_Int_concat(hl__types__ArrayBytes_Int,hl__types__ArrayBytes_Int);
String hl_types_ArrayBytes_Int_join(hl__types__ArrayBytes_Int,String);
vdynamic* hl_types_ArrayBytes_Int_pop(hl__types__ArrayBytes_Int);
int hl_types_ArrayBytes_Int_push(hl__types__ArrayBytes_Int,int);
void hl_types_ArrayBytes_Int_reverse(hl__types__ArrayBytes_Int);
vdynamic* hl_types_ArrayBytes_Int_shift(hl__types__ArrayBytes_Int);
void hl_types_ArrayBytes_Int_blit(hl__types__ArrayBytes_Int,int,hl__types__ArrayAccess,int,int);
hl__types__ArrayBase hl_types_ArrayBytes_Int_slice(hl__types__ArrayBytes_Int,int,vdynamic*);
void hl_types_ArrayBytes_Int_sort(hl__types__ArrayBytes_Int,vclosure*);
hl__types__ArrayBase hl_types_ArrayBytes_Int_splice(hl__types__ArrayBytes_Int,int,int);
String hl_types_ArrayBytes_Int_toString(hl__types__ArrayBytes_Int);
void hl_types_ArrayBytes_Int_unshift(hl__types__ArrayBytes_Int,int);
void hl_types_ArrayBytes_Int_insert(hl__types__ArrayBytes_Int,int,int);
bool hl_types_ArrayBytes_Int_contains(hl__types__ArrayBytes_Int,int);
bool hl_types_ArrayBytes_Int_remove(hl__types__ArrayBytes_Int,int);
int hl_types_ArrayBytes_Int_indexOf(hl__types__ArrayBytes_Int,int,vdynamic*);
int hl_types_ArrayBytes_Int_lastIndexOf(hl__types__ArrayBytes_Int,int,vdynamic*);
hl__types__ArrayBytes_Int hl_types_ArrayBytes_Int_copy(hl__types__ArrayBytes_Int);
haxe__iterators__ArrayIterator hl_types_ArrayBytes_Int_iterator(hl__types__ArrayBytes_Int);
haxe__iterators__ArrayKeyValueIterator hl_types_ArrayBytes_Int_keyValueIterator(hl__types__ArrayBytes_Int);
hl__types__ArrayDyn hl_types_ArrayBytes_Int_map(hl__types__ArrayBytes_Int,vclosure*);
hl__types__ArrayBytes_Int hl_types_ArrayBytes_Int_filter(hl__types__ArrayBytes_Int,vclosure*);
void hl_types_ArrayBytes_Int_resize(hl__types__ArrayBytes_Int,int);
vdynamic* hl_types_ArrayBytes_Int_getDyn(hl__types__ArrayBytes_Int,int);
void hl_types_ArrayBytes_Int_setDyn(hl__types__ArrayBytes_Int,int,vdynamic*);
int hl_types_ArrayBytes_Int_pushDyn(hl__types__ArrayBytes_Int,vdynamic*);
vdynamic* hl_types_ArrayBytes_Int_popDyn(hl__types__ArrayBytes_Int);
vdynamic* hl_types_ArrayBytes_Int_shiftDyn(hl__types__ArrayBytes_Int);
void hl_types_ArrayBytes_Int_unshiftDyn(hl__types__ArrayBytes_Int,vdynamic*);
void hl_types_ArrayBytes_Int_insertDyn(hl__types__ArrayBytes_Int,int,vdynamic*);
bool hl_types_ArrayBytes_Int_containsDyn(hl__types__ArrayBytes_Int,vdynamic*);
bool hl_types_ArrayBytes_Int_removeDyn(hl__types__ArrayBytes_Int,vdynamic*);
void hl_types_ArrayBytes_Int_sortDyn(hl__types__ArrayBytes_Int,vclosure*);
void hl_types_ArrayBytes_Int___expand(hl__types__ArrayBytes_Int,int);
String haxe_Log_formatOutput(vdynamic*,vvirtual*);
void haxe_Log_trace(vdynamic*,vvirtual*);
hl__types__ArrayObj hl_types_ArrayObj_concat(hl__types__ArrayObj,hl__types__ArrayObj);
String hl_types_ArrayObj_join(hl__types__ArrayObj,String);
bool hl_types_ArrayObj_isArrayObj(hl__types__ArrayObj);
vdynamic* hl_types_ArrayObj_pop(hl__types__ArrayObj);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
void hl_types_ArrayObj_reverse(hl__types__ArrayObj);
vdynamic* hl_types_ArrayObj_shift(hl__types__ArrayObj);
hl__types__ArrayBase hl_types_ArrayObj_slice(hl__types__ArrayObj,int,vdynamic*);
void hl_types_ArrayObj_sort(hl__types__ArrayObj,vclosure*);
hl__types__ArrayBase hl_types_ArrayObj_splice(hl__types__ArrayObj,int,int);
String hl_types_ArrayObj_toString(hl__types__ArrayObj);
void hl_types_ArrayObj_unshift(hl__types__ArrayObj,vdynamic*);
void hl_types_ArrayObj_insert(hl__types__ArrayObj,int,vdynamic*);
bool hl_types_ArrayObj_contains(hl__types__ArrayObj,vdynamic*);
bool hl_types_ArrayObj_remove(hl__types__ArrayObj,vdynamic*);
int hl_types_ArrayObj_indexOf(hl__types__ArrayObj,vdynamic*,vdynamic*);
void hl_types_ArrayObj_blit(hl__types__ArrayObj,int,hl__types__ArrayAccess,int,int);
int hl_types_ArrayObj_lastIndexOf(hl__types__ArrayObj,vdynamic*,vdynamic*);
hl__types__ArrayObj hl_types_ArrayObj_copy(hl__types__ArrayObj);
haxe__iterators__ArrayIterator hl_types_ArrayObj_iterator(hl__types__ArrayObj);
haxe__iterators__ArrayKeyValueIterator hl_types_ArrayObj_keyValueIterator(hl__types__ArrayObj);
hl__types__ArrayDyn hl_types_ArrayObj_map(hl__types__ArrayObj,vclosure*);
hl__types__ArrayObj hl_types_ArrayObj_filter(hl__types__ArrayObj,vclosure*);
void hl_types_ArrayObj_resize(hl__types__ArrayObj,int);
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);
vdynamic* hl_types_ArrayObj_getDyn(hl__types__ArrayObj,int);
void hl_types_ArrayObj_setDyn(hl__types__ArrayObj,int,vdynamic*);
int hl_types_ArrayObj_pushDyn(hl__types__ArrayObj,vdynamic*);
vdynamic* hl_types_ArrayObj_popDyn(hl__types__ArrayObj);
vdynamic* hl_types_ArrayObj_shiftDyn(hl__types__ArrayObj);
void hl_types_ArrayObj_unshiftDyn(hl__types__ArrayObj,vdynamic*);
void hl_types_ArrayObj_insertDyn(hl__types__ArrayObj,int,vdynamic*);
bool hl_types_ArrayObj_containsDyn(hl__types__ArrayObj,vdynamic*);
bool hl_types_ArrayObj_removeDyn(hl__types__ArrayObj,vdynamic*);
void hl_types_ArrayObj_sortDyn(hl__types__ArrayObj,vclosure*);
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
#include <haxe/ds/StringMap.h>
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
bool haxe_ds_StringMap_exists(haxe__ds__StringMap,String);
bool haxe_ds_StringMap_remove(haxe__ds__StringMap,String);
vvirtual* haxe_ds_StringMap_keys(haxe__ds__StringMap);
void haxe_ds_StringMap_new(haxe__ds__StringMap);
double Math_max(double,double);
double Math_min(double,double);
#include <_std/TestPlayer.h>
void TestPlayer_takeDamage(TestPlayer,int);
int TestPlayer_heal(TestPlayer,int);
void TestPlayer_new(TestPlayer,String,int);
void TestGame_addPoints(int);
int TestGame_getHighScore(void);
void TestGame_reset(void);
String Std_string(vdynamic*);
vdynamic* Std___add__(vdynamic*,vdynamic*);
#include <_std/StringBuf.h>
void StringBuf_new(StringBuf);
void StringBuf_add(StringBuf,vdynamic*);
void StringBuf_addChar(StringBuf,int);
String StringBuf_toString(StringBuf);
vbyte* StringBuf___string(StringBuf);
#include <_std/SysError.h>
void SysError_new(SysError,String);
String SysError_toString(SysError);
vbyte* SysError___string(SysError);
vbyte* hl__Bytes_Bytes_Impl__sub(vbyte*,int,int);
void Sys_println(vdynamic*);
bool Type_init(void);
#include <hl/Class.h>
hl__Class Type_initClass(hl_type*,hl_type*,vbyte*);
void Type_register(vbyte*,hl__BaseType);
#include <hl/Enum.h>
hl__Enum Type_initEnum(hl_type*,hl_type*);
void hl_types_ArrayObj_new(hl__types__ArrayObj);
#include <haxe/Exception.h>
void haxe_Exception_new(haxe__Exception,String,haxe__Exception,vdynamic*);
String haxe_Exception_toString(haxe__Exception);
String haxe_Exception_get_message(haxe__Exception);
vbyte* haxe_Exception___string(haxe__Exception);
varray* haxe_NativeStackTrace_exceptionStack(void);
void haxe_NativeStackTrace_saveStack(vdynamic*);
void haxe_ds_ArraySort_sort(hl__types__ArrayDyn,vclosure*);
void haxe_ds_ArraySort_rec(hl__types__ArrayDyn,vclosure*,int,int);
void haxe_ds_ArraySort_swap(hl__types__ArrayDyn,int,int);
void haxe_ds_ArraySort_doMerge(hl__types__ArrayDyn,vclosure*,int,int,int,int,int);
int haxe_ds_ArraySort_lower(hl__types__ArrayDyn,vclosure*,int,int,int);
int haxe_ds_ArraySort_upper(hl__types__ArrayDyn,vclosure*,int,int,int);
void haxe_ds_ArraySort_rotate(hl__types__ArrayDyn,vclosure*,int,int,int);
int haxe_ds_ArraySort_gcd(int,int);
#include <haxe/ds/_StringMap/StringMapKeysIterator.h>
void haxe_ds__StringMap_StringMapKeysIterator_new(haxe__ds___StringMap__StringMapKeysIterator,hl_bytes_map*);
bool haxe_ds__StringMap_StringMapKeysIterator_hasNext(haxe__ds___StringMap__StringMapKeysIterator);
String haxe_ds__StringMap_StringMapKeysIterator_next(haxe__ds___StringMap__StringMapKeysIterator);
#include <haxe/exceptions/PosException.h>
void haxe_exceptions_PosException_new(haxe__exceptions__PosException,String,haxe__Exception,vvirtual*);
String haxe_exceptions_PosException_toString(haxe__exceptions__PosException);
#include <haxe/exceptions/NotImplementedException.h>
void haxe_exceptions_NotImplementedException_new(haxe__exceptions__NotImplementedException,String,haxe__Exception,vvirtual*);
void haxe_iterators_ArrayIterator_new(haxe__iterators__ArrayIterator,hl__types__ArrayDyn);
bool haxe_iterators_ArrayIterator_hasNext(haxe__iterators__ArrayIterator);
vdynamic* haxe_iterators_ArrayIterator_next(haxe__iterators__ArrayIterator);
void haxe_iterators_ArrayKeyValueIterator_new(haxe__iterators__ArrayKeyValueIterator,hl__types__ArrayDyn);
#include <hl/NativeArrayIterator_Dynamic.h>
void hl_NativeArrayIterator_Dynamic_new(hl__NativeArrayIterator_Dynamic,varray*);
bool hl_NativeArrayIterator_Dynamic_hasNext(hl__NativeArrayIterator_Dynamic);
vdynamic* hl_NativeArrayIterator_Dynamic_next(hl__NativeArrayIterator_Dynamic);
#include <hl/NativeArrayIterator_Int.h>
void hl_NativeArrayIterator_Int_new(hl__NativeArrayIterator_Int,varray*);
bool hl_NativeArrayIterator_Int_hasNext(hl__NativeArrayIterator_Int);
int hl_NativeArrayIterator_Int_next(hl__NativeArrayIterator_Int);
hl__types__ArrayDyn hl_types_ArrayDyn_alloc(hl__types__ArrayBase,bool*);
void hl_types_ArrayBytes_Float_new(hl__types__ArrayBytes_Float);
int hl_types_ArrayBytes_Float_sort__$1(vclosure*,int,int);
#include <hl/types/BytesIterator_Float.h>
bool hl_types_BytesIterator_Float_hasNext(hl__types__BytesIterator_Float);
vdynamic* hl_types_BytesIterator_Float_next(hl__types__BytesIterator_Float);
void hl_types_BytesIterator_Float_new(hl__types__BytesIterator_Float,hl__types__ArrayBytes_Float);
int hl_types_ArrayBytes_Float_sortDyn__$1(vclosure*,double,double);
void hl_types_ArrayBytes_Int_new(hl__types__ArrayBytes_Int);
int hl_types_ArrayBytes_Int_sort__$1(vclosure*,double,double);
#include <hl/types/BytesIterator_Int.h>
bool hl_types_BytesIterator_Int_hasNext(hl__types__BytesIterator_Int);
vdynamic* hl_types_BytesIterator_Int_next(hl__types__BytesIterator_Int);
void hl_types_BytesIterator_Int_new(hl__types__BytesIterator_Int,hl__types__ArrayBytes_Int);
int hl_types_ArrayBytes_Int_sortDyn__$1(vclosure*,int,int);
void hl_types_ArrayBytes_hl_F32_new(hl__types__ArrayBytes_hl_F32);
int hl_types_ArrayBytes_hl_F32_sort__$1(vclosure*,int,int);
int hl_types_ArrayBytes_hl_F32_sort__$2(vclosure*,double,double);
#include <hl/types/BytesIterator_hl_F32.h>
bool hl_types_BytesIterator_hl_F32_hasNext(hl__types__BytesIterator_hl_F32);
vdynamic* hl_types_BytesIterator_hl_F32_next(hl__types__BytesIterator_hl_F32);
void hl_types_BytesIterator_hl_F32_new(hl__types__BytesIterator_hl_F32,hl__types__ArrayBytes_hl_F32);
int hl_types_ArrayBytes_hl_F32_sortDyn__$1(vclosure*,float,float);
void hl_types_ArrayBytes_hl_UI16_new(hl__types__ArrayBytes_hl_UI16);
int hl_types_ArrayBytes_hl_UI16_sort__$1(vclosure*,int,int);
int hl_types_ArrayBytes_hl_UI16_sort__$2(vclosure*,double,double);
#include <hl/types/BytesIterator_hl_UI16.h>
bool hl_types_BytesIterator_hl_UI16_hasNext(hl__types__BytesIterator_hl_UI16);
vdynamic* hl_types_BytesIterator_hl_UI16_next(hl__types__BytesIterator_hl_UI16);
void hl_types_BytesIterator_hl_UI16_new(hl__types__BytesIterator_hl_UI16,hl__types__ArrayBytes_hl_UI16);
int hl_types_ArrayBytes_hl_UI16_sortDyn__$1(vclosure*,unsigned short,unsigned short);
#include <hl/types/ArrayDynIterator.h>
void hl_types_ArrayDynIterator_new(hl__types__ArrayDynIterator,hl__types__ArrayBase);
bool hl_types_ArrayDynIterator_hasNext(hl__types__ArrayDynIterator);
vdynamic* hl_types_ArrayDynIterator_next(hl__types__ArrayDynIterator);
void hl_types_ArrayDyn_new(hl__types__ArrayDyn);
#include <hl/types/ArrayObjIterator.h>
void hl_types_ArrayObjIterator_new(hl__types__ArrayObjIterator,hl__types__ArrayObj);
bool hl_types_ArrayObjIterator_hasNext(hl__types__ArrayObjIterator);
vdynamic* hl_types_ArrayObjIterator_next(hl__types__ArrayObjIterator);
void fun$init(void);
extern hl_type t$fun_0cf7b0f;
extern hl_type t$fun_2e8f00c;
extern hl_type t$fun_4be1f96;
extern hl_type t$fun_898a634;
extern hl_type t$fun_3321050;
extern hl_type t$fun_877a08a;
extern hl_type t$fun_c2729d3;
extern hl_type t$fun_07a8a5d;
extern hl_type t$fun_474f12c;
extern hl_type t$fun_735e9b2;
extern hl_type t$fun_431710a;
extern hl_type t$fun_7daa93c;
extern hl_type t$fun_83f90f5;
extern hl_type t$fun_07b476c;
extern hl_type t$fun_2e5590a;
extern hl_type t$fun_0b873a8;
extern hl_type t$fun_7180aec;
extern hl_type t$fun_fab01bb;
extern hl_type t$fun_67512d4;
extern hl_type t$fun_d420bf5;
extern hl_type t$fun_9dd8397;
extern hl_type t$fun_ad6559a;
extern hl_type t$fun_7b48b4f;
extern hl_type t$fun_146041c;
extern hl_type t$fun_50a2a57;
extern hl_type t$fun_359a2b1;
extern hl_type t$fun_028fcdb;
extern hl_type t$fun_66dc44f;
extern hl_type t$fun_4a34ed4;
extern hl_type t$fun_9b99f83;
extern hl_type t$fun_1a31d49;
extern hl_type t$fun_e274397;
extern hl_type t$fun_ff5291f;
extern hl_type t$fun_90cc865;
extern hl_type t$fun_8512fa6;
extern hl_type t$fun_a1597d2;
extern hl_type t$fun_cd620e0;
extern hl_type t$fun_05c5c70;
extern hl_type t$fun_273802e;
extern hl_type t$fun_6b8f2f5;
extern hl_type t$fun_649d6d6;
extern hl_type t$fun_d7336af;
extern hl_type t$fun_7874b8f;
extern hl_type t$fun_41dc717;
extern hl_type t$fun_bb9de1f;
extern hl_type t$fun_456327b;
extern hl_type t$fun_2728842;
extern hl_type t$fun_31e3720;
extern hl_type t$fun_e7e1261;
extern hl_type t$fun_6a92a5c;
extern hl_type t$fun_887f033;
extern hl_type t$fun_5fd9564;
extern hl_type t$fun_c2d7059;
extern hl_type t$fun_f72790f;
extern hl_type t$fun_e4326cf;
extern hl_type t$fun_8722abf;
extern hl_type t$fun_057735d;
extern hl_type t$fun_5a4a25b;
extern hl_type t$fun_9d4e5fc;
extern hl_type t$fun_d16759d;
extern hl_type t$fun_4eb6a91;
extern hl_type t$fun_4ddc06d;
extern hl_type t$fun_61faa0c;
extern hl_type t$fun_0924a07;
extern hl_type t$fun_6526076;
extern hl_type t$fun_cc3ac55;
extern hl_type t$fun_94ccc5b;
extern hl_type t$fun_e2ad7d5;
extern hl_type t$fun_869b919;
extern hl_type t$fun_e3ed9bc;
extern hl_type t$fun_e0b429b;
extern hl_type t$fun_7d88847;
extern hl_type t$fun_0a33ad9;
extern hl_type t$fun_d3fbc0f;
extern hl_type t$fun_d3bd0e8;
extern hl_type t$fun_b188caa;
extern hl_type t$fun_0086861;
extern hl_type t$fun_84e48f9;
extern hl_type t$fun_6d41e68;
extern hl_type t$fun_21e3130;
extern hl_type t$fun_cd61d64;
extern hl_type t$fun_f18ff1f;
extern hl_type t$fun_33a57e8;
extern hl_type t$fun_7b0f58c;
extern hl_type t$fun_a8827a8;
extern hl_type t$fun_477df90;
extern hl_type t$fun_d666783;
extern hl_type t$fun_e100368;
extern hl_type t$fun_fa4ede4;
extern hl_type t$fun_0220b44;
extern hl_type t$fun_5645aa5;
extern hl_type t$fun_cec3dfe;
extern hl_type t$fun_6c408ca;
extern hl_type t$fun_f1dc20f;
extern hl_type t$fun_628a32f;
extern hl_type t$fun_2de193f;
extern hl_type t$fun_c5f8e15;
extern hl_type t$fun_4f52002;
extern hl_type t$fun_ff2a1e0;
extern hl_type t$fun_657cda2;
extern hl_type t$fun_b7ebdbb;
extern hl_type t$fun_a7c0043;
extern hl_type t$fun_1ac3d2f;
extern hl_type t$fun_58500dd;
extern hl_type t$fun_cd6ee2b;
extern hl_type t$fun_0afa491;
extern hl_type t$fun_043889e;
extern hl_type t$fun_cbfbb11;
extern hl_type t$fun_581014c;
extern hl_type t$fun_7516ce9;
extern hl_type t$fun_b0730e5;
extern hl_type t$fun_6609876;
extern hl_type t$fun_fce9cf4;
extern hl_type t$fun_10f1671;
extern hl_type t$fun_41f7c18;
extern hl_type t$fun_938f64e;
extern hl_type t$fun_e368050;
extern hl_type t$fun_1684400;
extern hl_type t$fun_73888f1;
extern hl_type t$fun_0209fd2;
extern hl_type t$fun_4cc41a0;
extern hl_type t$fun_fbd527b;
extern hl_type t$fun_2ee88c6;
extern hl_type t$fun_90b138e;
extern hl_type t$fun_b237b0e;
extern hl_type t$fun_06eb456;
extern hl_type t$fun_9767ea2;
extern hl_type t$fun_7f2df24;
extern hl_type t$fun_46b3fe7;
extern hl_type t$fun_0f6e688;
extern hl_type t$fun_712c9bd;
extern hl_type t$fun_1a69e40;
extern hl_type t$fun_05165e0;
extern hl_type t$fun_1bfe27a;
extern hl_type t$fun_48512d4;
extern hl_type t$fun_3218a3e;
extern hl_type t$fun_bc05abb;
extern hl_type t$fun_d042089;
extern hl_type t$fun_6748920;
extern hl_type t$fun_adaff03;
extern hl_type t$fun_6817c8d;
extern hl_type t$fun_58f9a05;
extern hl_type t$fun_5d217f8;
extern hl_type t$fun_a8583d9;
extern hl_type t$fun_6f78cb5;
extern hl_type t$fun_6324bd7;
extern hl_type t$fun_8f299ff;
extern hl_type t$fun_73d7da9;
extern hl_type t$fun_779bb7a;
extern hl_type t$fun_0014963;
extern hl_type t$fun_e1c3662;
extern hl_type t$fun_88c3641;
extern hl_type t$fun_79361ea;
extern hl_type t$fun_9ada1e2;
extern hl_type t$fun_25bf129;
extern hl_type t$fun_6fe8950;
extern hl_type t$fun_76c9422;
extern hl_type t$fun_bb92de8;
extern hl_type t$fun_2ce2967;
extern hl_type t$fun_ee67120;
extern hl_type t$fun_bc56d4c;
extern hl_type t$fun_7d470df;
extern hl_type t$fun_59cf8ee;
extern hl_type t$fun_4feb77e;
extern hl_type t$fun_d61d4d0;
extern hl_type t$fun_0f7dabe;
extern hl_type t$fun_98301c5;
extern hl_type t$fun_cf4161f;
extern hl_type t$fun_1e06d39;
extern hl_type t$fun_c0df3eb;
extern hl_type t$fun_a730fbb;
extern hl_type t$fun_50caa91;
extern hl_type t$fun_fd4a424;
extern hl_type t$fun_e880a67;
extern hl_type t$fun_e35f4e4;
extern hl_type t$fun_4f1a968;
extern hl_type t$fun_358bb66;
extern hl_type t$fun_439b121;
extern hl_type t$fun_5daea2a;
extern hl_type t$fun_1bb5e7a;
extern hl_type t$fun_c9b325a;
extern hl_type t$fun_746eb80;
extern hl_type t$fun_ffbcb45;
extern hl_type t$fun_7fbe2c6;
extern hl_type t$fun_715d8bf;
extern hl_type t$fun_36ccd09;
extern hl_type t$fun_246e7a0;
extern hl_type t$fun_0611c86;
extern hl_type t$fun_3bd7056;
extern hl_type t$fun_0d2ac19;
extern hl_type t$fun_f4509ab;
extern hl_type t$fun_c0b2bf7;
extern hl_type t$fun_f334ec9;
extern hl_type t$fun_4052dad;
extern hl_type t$fun_ed49d23;
extern hl_type t$fun_65d82e0;
extern hl_type t$fun_86af97c;
extern hl_type t$fun_2424150;
extern hl_type t$fun_4c2da7d;
extern hl_type t$fun_a163fa2;
extern hl_type t$fun_294d21b;
extern hl_type t$fun_1c0676c;
extern hl_type t$fun_b368daf;
extern hl_type t$fun_352a843;
extern hl_type t$fun_5d45b3d;
extern hl_type t$fun_e670c8f;
extern hl_type t$fun_c079ced;
extern hl_type t$fun_b8dcb1d;
extern hl_type t$fun_e5a2d8d;
extern hl_type t$fun_431ce16;
extern hl_type t$fun_0baea77;
extern hl_type t$fun_63b98a1;
extern hl_type t$fun_ab25373;
extern hl_type t$fun_a0ea711;
extern hl_type t$fun_8249ca6;
extern hl_type t$fun_9c2ac14;
extern hl_type t$fun_cb6e3d3;
extern hl_type t$fun_b7334d8;
extern hl_type t$fun_baf777f;
extern hl_type t$fun_e7027a9;
extern hl_type t$fun_1793431;
extern hl_type t$fun_1569556;
extern hl_type t$fun_8bbbd94;
extern hl_type t$fun_75c9212;
extern hl_type t$fun_491b92b;
extern hl_type t$fun_f903b64;
extern hl_type t$fun_40779dc;
extern hl_type t$fun_abea61a;
extern hl_type t$fun_1b2ab6c;
extern hl_type t$fun_b6465b0;
extern hl_type t$fun_e0a06a5;
extern hl_type t$fun_8502ba2;
extern hl_type t$fun_64963c5;
extern hl_type t$fun_2a2b436;
extern hl_type t$fun_fdf49c0;
extern hl_type t$fun_eaaef2e;
extern hl_type t$fun_926956b;
extern hl_type t$fun_b0764ef;
extern hl_type t$fun_544176c;
extern hl_type t$fun_feba9b0;
extern hl_type t$fun_0ecc9bc;
extern hl_type t$fun_10aec05;
extern hl_type t$fun_8186749;
extern hl_type t$fun_17f31ef;
extern hl_type t$fun_95d9f81;
extern hl_type t$fun_8f51bbf;
extern hl_type t$fun_e1e3de0;
extern hl_type t$fun_ed8c8ee;
extern hl_type t$fun_23e58fc;
extern hl_type t$fun_2b03f8e;
extern hl_type t$fun_b7665f4;
extern hl_type t$fun_6b7e1eb;
extern hl_type t$fun_0b37ebf;
extern hl_type t$fun_81a6bcb;
extern hl_type t$fun_3ec66f4;
extern hl_type t$fun_f1e0fdc;
extern hl_type t$fun_06076c9;
extern hl_type t$fun_10909c7;
extern hl_type t$fun_8245b77;
extern hl_type t$fun_95e430c;
extern hl_type t$fun_8308e1f;
extern hl_type t$fun_21d4cdf;
extern hl_type t$fun_1ef6dfe;
extern hl_type t$fun_1f02863;
extern hl_type t$fun_be5ea00;
extern hl_type t$fun_4a06caf;
extern hl_type t$fun_99dc1e9;
extern hl_type t$fun_16e5dde;
extern hl_type t$fun_f729cf8;
extern hl_type t$fun_818a08a;
extern hl_type t$fun_6c16e15;
extern hl_type t$fun_fd3b467;
extern hl_type t$fun_4c57111;
extern hl_type t$fun_a4d13ad;
extern hl_type t$fun_078836b;
extern hl_type t$fun_e705f35;
extern hl_type t$fun_047f094;
extern hl_type t$fun_62da9da;
extern hl_type t$fun_0efb18a;
extern hl_type t$fun_3aeb07d;
extern hl_type t$fun_6c047b1;
extern hl_type t$fun_0d9b19a;
extern hl_type t$fun_d800c38;
extern hl_type t$fun_cc70830;
extern hl_type t$fun_10c6fb3;
extern hl_type t$fun_99481a7;
extern hl_type t$fun_2533487;
extern hl_type t$fun_ed935ff;
extern hl_type t$fun_ff87c1a;
extern hl_type t$fun_7a5ad5f;
extern hl_type t$fun_5823d1c;
extern hl_type t$fun_1461878;
extern hl_type t$fun_40d3b9d;
extern hl_type t$fun_777d349;
extern hl_type t$fun_e82aa58;
extern hl_type t$fun_f7fbc74;
extern hl_type t$fun_17cbfdc;
extern hl_type t$fun_026a163;
extern hl_type t$fun_5138cad;
extern hl_type t$fun_274adf2;
extern hl_type t$fun_b51d32d;
extern hl_type t$fun_cae6940;
extern hl_type t$fun_0223e89;
extern hl_type t$fun_d6dbe42;
extern hl_type t$fun_cf72872;
extern hl_type t$fun_064ef4b;
extern hl_type t$fun_3a8cb27;
extern hl_type t$fun_56a2bdf;
extern hl_type t$fun_1f6ee54;
extern hl_type t$fun_677a3a6;
extern hl_type t$fun_c880cd2;
extern hl_type t$fun_f66e73a;
extern hl_type t$fun_df79850;
extern hl_type t$fun_f38af0d;
extern hl_type t$fun_3193805;
extern hl_type t$fun_83a2015;
extern hl_type t$fun_c854326;
extern hl_type t$fun_0e7b31e;
extern hl_type t$fun_63e5768;
extern hl_type t$fun_44163b0;
extern hl_type t$fun_622a6a5;
extern hl_type t$fun_0094d0c;
extern hl_type t$fun_2795670;
extern hl_type t$fun_bfddde4;
extern hl_type t$fun_585f248;
extern hl_type t$hl_types_ArrayObj;
extern hl_type t$_dyn;

void *hl_functions_ptrs[] = {String_toUpperCase,\
	String_toLowerCase,\
	String_charAt,\
	String_charCodeAt,\
	String_findChar,\
	String_indexOf,\
	String_lastIndexOf,\
	String_split,\
	String_substr,\
	String_substring,\
	String_toString,\
	String_toUtf8,\
	String___string,\
	String___compare,\
	hl_BaseType_check,\
	String_fromCharCode,\
	String___alloc__,\
	String_call_toString,\
	String_fromUCS2,\
	String_fromUTF8,\
	String___add__,\
	String_new,\
	hl_date_new,\
	hl_date_to_string,\
	Date_new,\
	Date_toString,\
	Date___string,\
	HlcTestSuite_assert,\
	HlcTestSuite_testBasicTypes,\
	HlcTestSuite_testArrays,\
	HlcTestSuite_testMaps,\
	HlcTestSuite_testStrings,\
	HlcTestSuite_testMath,\
	HlcTestSuite_testClasses,\
	HlcTestSuite_testStaticMembers,\
	HlcTestSuite_testEnums,\
	HlcTestSuite_testExceptions,\
	HlcTestSuite_main,\
	hl_types_ArrayAccess_getDyn,\
	hl_types_ArrayAccess_setDyn,\
	hl_types_ArrayAccess_blit,\
	hl_types_ArrayDyn_get_length,\
	hl_types_ArrayDyn_getDyn,\
	hl_types_ArrayDyn_setDyn,\
	hl_types_ArrayDyn_blit,\
	hl_types_ArrayDyn_concat,\
	hl_types_ArrayDyn_join,\
	hl_types_ArrayDyn_pop,\
	hl_types_ArrayDyn_push,\
	hl_types_ArrayDyn_reverse,\
	hl_types_ArrayDyn_resize,\
	hl_types_ArrayDyn_shift,\
	hl_types_ArrayDyn_slice,\
	hl_types_ArrayDyn_sort,\
	hl_types_ArrayDyn_splice,\
	hl_types_ArrayDyn_toString,\
	hl_types_ArrayDyn_unshift,\
	hl_types_ArrayDyn_insert,\
	hl_types_ArrayDyn_contains,\
	hl_types_ArrayDyn_remove,\
	hl_types_ArrayDyn_indexOf,\
	hl_types_ArrayDyn_lastIndexOf,\
	hl_types_ArrayDyn_copy,\
	hl_types_ArrayDyn_iterator,\
	hl_types_ArrayDyn_keyValueIterator,\
	hl_types_ArrayDyn_map,\
	hl_types_ArrayDyn_filter,\
	hl_types_ArrayDyn___get_field,\
	hl_types_ArrayDyn___cast,\
	hl_types_ArrayDyn___compare,\
	hl_types_ArrayDyn___string,\
	hl_types_ArrayBase_pushDyn,\
	hl_types_ArrayBase_popDyn,\
	hl_types_ArrayBase_shiftDyn,\
	hl_types_ArrayBase_unshiftDyn,\
	hl_types_ArrayBase_insertDyn,\
	hl_types_ArrayBase_containsDyn,\
	hl_types_ArrayBase_removeDyn,\
	hl_types_ArrayBase_sortDyn,\
	hl_types_ArrayBase_slice,\
	hl_types_ArrayBase_splice,\
	hl_types_ArrayBase_join,\
	hl_types_ArrayBase_reverse,\
	hl_types_ArrayBase_resize,\
	hl_types_ArrayBase_toString,\
	hl_types_ArrayBase___cast,\
	hl_types_ArrayBase_isArrayObj,\
	hl_types_ArrayBase___string,\
	hl_types_ArrayBase_allocI32,\
	hl_types_ArrayBase_allocUI16,\
	hl_types_ArrayBase_allocF32,\
	hl_types_ArrayBase_allocF64,\
	hl_types_ArrayBytes_Float_concat,\
	hl_types_ArrayBytes_Float_join,\
	hl_types_ArrayBytes_Float_pop,\
	hl_types_ArrayBytes_Float_push,\
	hl_types_ArrayBytes_Float_reverse,\
	hl_types_ArrayBytes_Float_shift,\
	hl_types_ArrayBytes_Float_blit,\
	hl_types_ArrayBytes_Float_slice,\
	hl_types_ArrayBytes_Float_sort,\
	hl_types_ArrayBytes_Float_splice,\
	hl_types_ArrayBytes_Float_toString,\
	hl_types_ArrayBytes_Float_unshift,\
	hl_types_ArrayBytes_Float_insert,\
	hl_types_ArrayBytes_Float_contains,\
	hl_types_ArrayBytes_Float_remove,\
	hl_types_ArrayBytes_Float_indexOf,\
	hl_types_ArrayBytes_Float_lastIndexOf,\
	hl_types_ArrayBytes_Float_copy,\
	hl_types_ArrayBytes_Float_iterator,\
	hl_types_ArrayBytes_Float_keyValueIterator,\
	hl_types_ArrayBytes_Float_map,\
	hl_types_ArrayBytes_Float_filter,\
	hl_types_ArrayBytes_Float_resize,\
	hl_types_ArrayBytes_Float_getDyn,\
	hl_types_ArrayBytes_Float_setDyn,\
	hl_types_ArrayBytes_Float_pushDyn,\
	hl_types_ArrayBytes_Float_popDyn,\
	hl_types_ArrayBytes_Float_shiftDyn,\
	hl_types_ArrayBytes_Float_unshiftDyn,\
	hl_types_ArrayBytes_Float_insertDyn,\
	hl_types_ArrayBytes_Float_containsDyn,\
	hl_types_ArrayBytes_Float_removeDyn,\
	hl_types_ArrayBytes_Float_sortDyn,\
	hl_types_ArrayBytes_Float___expand,\
	hl_types_ArrayBytes_hl_F32_concat,\
	hl_types_ArrayBytes_hl_F32_join,\
	hl_types_ArrayBytes_hl_F32_pop,\
	hl_types_ArrayBytes_hl_F32_push,\
	hl_types_ArrayBytes_hl_F32_reverse,\
	hl_types_ArrayBytes_hl_F32_shift,\
	hl_types_ArrayBytes_hl_F32_blit,\
	hl_types_ArrayBytes_hl_F32_slice,\
	hl_types_ArrayBytes_hl_F32_sort,\
	hl_types_ArrayBytes_hl_F32_splice,\
	hl_types_ArrayBytes_hl_F32_toString,\
	hl_types_ArrayBytes_hl_F32_unshift,\
	hl_types_ArrayBytes_hl_F32_insert,\
	hl_types_ArrayBytes_hl_F32_contains,\
	hl_types_ArrayBytes_hl_F32_remove,\
	hl_types_ArrayBytes_hl_F32_indexOf,\
	hl_types_ArrayBytes_hl_F32_lastIndexOf,\
	hl_types_ArrayBytes_hl_F32_copy,\
	hl_types_ArrayBytes_hl_F32_iterator,\
	hl_types_ArrayBytes_hl_F32_keyValueIterator,\
	hl_types_ArrayBytes_hl_F32_map,\
	hl_types_ArrayBytes_hl_F32_filter,\
	hl_types_ArrayBytes_hl_F32_resize,\
	hl_types_ArrayBytes_hl_F32_getDyn,\
	hl_types_ArrayBytes_hl_F32_setDyn,\
	hl_types_ArrayBytes_hl_F32_pushDyn,\
	hl_types_ArrayBytes_hl_F32_popDyn,\
	hl_types_ArrayBytes_hl_F32_shiftDyn,\
	hl_types_ArrayBytes_hl_F32_unshiftDyn,\
	hl_types_ArrayBytes_hl_F32_insertDyn,\
	hl_types_ArrayBytes_hl_F32_containsDyn,\
	hl_types_ArrayBytes_hl_F32_removeDyn,\
	hl_types_ArrayBytes_hl_F32_sortDyn,\
	hl_types_ArrayBytes_hl_F32___expand,\
	hl_types_ArrayBytes_hl_UI16_concat,\
	hl_types_ArrayBytes_hl_UI16_join,\
	hl_types_ArrayBytes_hl_UI16_pop,\
	hl_types_ArrayBytes_hl_UI16_push,\
	hl_types_ArrayBytes_hl_UI16_reverse,\
	hl_types_ArrayBytes_hl_UI16_shift,\
	hl_types_ArrayBytes_hl_UI16_blit,\
	hl_types_ArrayBytes_hl_UI16_slice,\
	hl_types_ArrayBytes_hl_UI16_sort,\
	hl_types_ArrayBytes_hl_UI16_splice,\
	hl_types_ArrayBytes_hl_UI16_toString,\
	hl_types_ArrayBytes_hl_UI16_unshift,\
	hl_types_ArrayBytes_hl_UI16_insert,\
	hl_types_ArrayBytes_hl_UI16_contains,\
	hl_types_ArrayBytes_hl_UI16_remove,\
	hl_types_ArrayBytes_hl_UI16_indexOf,\
	hl_types_ArrayBytes_hl_UI16_lastIndexOf,\
	hl_types_ArrayBytes_hl_UI16_copy,\
	hl_types_ArrayBytes_hl_UI16_iterator,\
	hl_types_ArrayBytes_hl_UI16_keyValueIterator,\
	hl_types_ArrayBytes_hl_UI16_map,\
	hl_types_ArrayBytes_hl_UI16_filter,\
	hl_types_ArrayBytes_hl_UI16_resize,\
	hl_types_ArrayBytes_hl_UI16_getDyn,\
	hl_types_ArrayBytes_hl_UI16_setDyn,\
	hl_types_ArrayBytes_hl_UI16_pushDyn,\
	hl_types_ArrayBytes_hl_UI16_popDyn,\
	hl_types_ArrayBytes_hl_UI16_shiftDyn,\
	hl_types_ArrayBytes_hl_UI16_unshiftDyn,\
	hl_types_ArrayBytes_hl_UI16_insertDyn,\
	hl_types_ArrayBytes_hl_UI16_containsDyn,\
	hl_types_ArrayBytes_hl_UI16_removeDyn,\
	hl_types_ArrayBytes_hl_UI16_sortDyn,\
	hl_types_ArrayBytes_hl_UI16___expand,\
	hl_types_ArrayBytes_Int_concat,\
	hl_types_ArrayBytes_Int_join,\
	hl_types_ArrayBytes_Int_pop,\
	hl_types_ArrayBytes_Int_push,\
	hl_types_ArrayBytes_Int_reverse,\
	hl_types_ArrayBytes_Int_shift,\
	hl_types_ArrayBytes_Int_blit,\
	hl_types_ArrayBytes_Int_slice,\
	hl_types_ArrayBytes_Int_sort,\
	hl_types_ArrayBytes_Int_splice,\
	hl_types_ArrayBytes_Int_toString,\
	hl_types_ArrayBytes_Int_unshift,\
	hl_types_ArrayBytes_Int_insert,\
	hl_types_ArrayBytes_Int_contains,\
	hl_types_ArrayBytes_Int_remove,\
	hl_types_ArrayBytes_Int_indexOf,\
	hl_types_ArrayBytes_Int_lastIndexOf,\
	hl_types_ArrayBytes_Int_copy,\
	hl_types_ArrayBytes_Int_iterator,\
	hl_types_ArrayBytes_Int_keyValueIterator,\
	hl_types_ArrayBytes_Int_map,\
	hl_types_ArrayBytes_Int_filter,\
	hl_types_ArrayBytes_Int_resize,\
	hl_types_ArrayBytes_Int_getDyn,\
	hl_types_ArrayBytes_Int_setDyn,\
	hl_types_ArrayBytes_Int_pushDyn,\
	hl_types_ArrayBytes_Int_popDyn,\
	hl_types_ArrayBytes_Int_shiftDyn,\
	hl_types_ArrayBytes_Int_unshiftDyn,\
	hl_types_ArrayBytes_Int_insertDyn,\
	hl_types_ArrayBytes_Int_containsDyn,\
	hl_types_ArrayBytes_Int_removeDyn,\
	hl_types_ArrayBytes_Int_sortDyn,\
	hl_types_ArrayBytes_Int___expand,\
	haxe_Log_formatOutput,\
	haxe_Log_trace,\
	hl_alloc_bytes,\
	hl_types_ArrayObj_concat,\
	hl_types_ArrayObj_join,\
	hl_types_ArrayObj_isArrayObj,\
	hl_types_ArrayObj_pop,\
	hl_types_ArrayObj_push,\
	hl_types_ArrayObj_reverse,\
	hl_types_ArrayObj_shift,\
	hl_types_ArrayObj_slice,\
	hl_types_ArrayObj_sort,\
	hl_types_ArrayObj_splice,\
	hl_types_ArrayObj_toString,\
	hl_types_ArrayObj_unshift,\
	hl_types_ArrayObj_insert,\
	hl_types_ArrayObj_contains,\
	hl_types_ArrayObj_remove,\
	hl_types_ArrayObj_indexOf,\
	hl_types_ArrayObj_blit,\
	hl_types_ArrayObj_lastIndexOf,\
	hl_types_ArrayObj_copy,\
	hl_types_ArrayObj_iterator,\
	hl_types_ArrayObj_keyValueIterator,\
	hl_types_ArrayObj_map,\
	hl_types_ArrayObj_filter,\
	hl_types_ArrayObj_resize,\
	hl_types_ArrayObj___expand,\
	hl_types_ArrayObj_getDyn,\
	hl_types_ArrayObj_setDyn,\
	hl_types_ArrayObj_pushDyn,\
	hl_types_ArrayObj_popDyn,\
	hl_types_ArrayObj_shiftDyn,\
	hl_types_ArrayObj_unshiftDyn,\
	hl_types_ArrayObj_insertDyn,\
	hl_types_ArrayObj_containsDyn,\
	hl_types_ArrayObj_removeDyn,\
	hl_types_ArrayObj_sortDyn,\
	hl_alloc_array,\
	hl_types_ArrayObj_alloc,\
	haxe_ds_StringMap_set,\
	haxe_ds_StringMap_get,\
	haxe_ds_StringMap_exists,\
	haxe_ds_StringMap_remove,\
	haxe_ds_StringMap_keys,\
	haxe_ds_StringMap_new,\
	hl_math_abs,\
	Math_max,\
	Math_min,\
	hl_math_round,\
	hl_math_sqrt,\
	TestPlayer_takeDamage,\
	TestPlayer_heal,\
	TestPlayer_new,\
	TestGame_addPoints,\
	TestGame_getHighScore,\
	TestGame_reset,\
	hl_itos,\
	hl_math_isnan,\
	hl_rnd_init_system,\
	Std_string,\
	hl_value_to_string,\
	Std___add__,\
	hl_alloc_bytes,\
	hl_ucs2length,\
	hl_utf8_to_utf16,\
	hl_bytes_blit,\
	hl_ucs2_upper,\
	hl_ucs2_lower,\
	hl_bytes_find,\
	hl_bytes_compare,\
	hl_utf16_to_utf8,\
	hl_ptr_compare,\
	hl_bytes_compare16,\
	StringBuf_new,\
	StringBuf_add,\
	StringBuf_addChar,\
	StringBuf_toString,\
	StringBuf___string,\
	SysError_new,\
	SysError_toString,\
	SysError___string,\
	hl_bytes_fill,\
	hl_bsort_i32,\
	hl_bsort_f64,\
	hl__Bytes_Bytes_Impl__sub,\
	Sys_println,\
	hl_sys_print,\
	hl_sys_utf8_path,\
	Type_init,\
	hl_hballoc,\
	Type_initClass,\
	hl_type_get_global,\
	hl_alloc_obj,\
	hl_type_set_global,\
	Type_register,\
	Type_initEnum,\
	hl_type_enum_values,\
	hl_type_name,\
	hl_types_ArrayObj_new,\
	hl_type_enum_fields,\
	hl_hbset,\
	haxe_Exception_new,\
	haxe_Exception_toString,\
	haxe_Exception_get_message,\
	haxe_Exception___string,\
	haxe_NativeStackTrace_exceptionStack,\
	hl_call_stack_raw,\
	hl_array_blit,\
	haxe_NativeStackTrace_saveStack,\
	hl_exception_stack_raw,\
	haxe_ds_ArraySort_sort,\
	haxe_ds_ArraySort_rec,\
	haxe_ds_ArraySort_swap,\
	haxe_ds_ArraySort_doMerge,\
	haxe_ds_ArraySort_lower,\
	haxe_ds_ArraySort_upper,\
	haxe_ds_ArraySort_rotate,\
	haxe_ds_ArraySort_gcd,\
	haxe_ds__StringMap_StringMapKeysIterator_new,\
	haxe_ds__StringMap_StringMapKeysIterator_hasNext,\
	haxe_ds__StringMap_StringMapKeysIterator_next,\
	hl_hbkeys,\
	hl_hbget,\
	hl_hbexists,\
	hl_hbremove,\
	haxe_exceptions_PosException_new,\
	haxe_exceptions_PosException_toString,\
	haxe_exceptions_NotImplementedException_new,\
	haxe_iterators_ArrayIterator_new,\
	haxe_iterators_ArrayIterator_hasNext,\
	haxe_iterators_ArrayIterator_next,\
	haxe_iterators_ArrayKeyValueIterator_new,\
	hl_obj_get_field,\
	hl_obj_set_field,\
	hl_obj_has_field,\
	hl_obj_delete_field,\
	hl_call_method,\
	hl_get_closure_value,\
	hl_make_closure,\
	hl_no_closure,\
	hl_value_cast,\
	hl_make_var_args,\
	hl_get_virtual_value,\
	hl_set_error_handler,\
	hl_breakpoint,\
	hl_sys_is64,\
	hl_is_prim_loaded,\
	hl_mem_compact,\
	hl_sys_check_reload,\
	hl_type_safe_cast,\
	hl_array_type,\
	hl_NativeArrayIterator_Dynamic_new,\
	hl_NativeArrayIterator_Dynamic_hasNext,\
	hl_NativeArrayIterator_Dynamic_next,\
	hl_NativeArrayIterator_Int_new,\
	hl_NativeArrayIterator_Int_hasNext,\
	hl_NativeArrayIterator_Int_next,\
	hl_types_ArrayDyn_alloc,\
	hl_types_ArrayBytes_Float_new,\
	hl_types_ArrayBytes_Float_sort__$1,\
	hl_types_BytesIterator_Float_hasNext,\
	hl_types_BytesIterator_Float_next,\
	hl_types_BytesIterator_Float_new,\
	hl_types_ArrayBytes_Float_sortDyn__$1,\
	hl_types_ArrayBytes_Int_new,\
	hl_types_ArrayBytes_Int_sort__$1,\
	hl_types_BytesIterator_Int_hasNext,\
	hl_types_BytesIterator_Int_next,\
	hl_types_BytesIterator_Int_new,\
	hl_types_ArrayBytes_Int_sortDyn__$1,\
	hl_types_ArrayBytes_hl_F32_new,\
	hl_types_ArrayBytes_hl_F32_sort__$1,\
	hl_types_ArrayBytes_hl_F32_sort__$2,\
	hl_types_BytesIterator_hl_F32_hasNext,\
	hl_types_BytesIterator_hl_F32_next,\
	hl_types_BytesIterator_hl_F32_new,\
	hl_types_ArrayBytes_hl_F32_sortDyn__$1,\
	hl_types_ArrayBytes_hl_UI16_new,\
	hl_types_ArrayBytes_hl_UI16_sort__$1,\
	hl_types_ArrayBytes_hl_UI16_sort__$2,\
	hl_types_BytesIterator_hl_UI16_hasNext,\
	hl_types_BytesIterator_hl_UI16_next,\
	hl_types_BytesIterator_hl_UI16_new,\
	hl_types_ArrayBytes_hl_UI16_sortDyn__$1,\
	hl_types_ArrayDynIterator_new,\
	hl_types_ArrayDynIterator_hasNext,\
	hl_types_ArrayDynIterator_next,\
	hl_types_ArrayDyn_new,\
	hl_types_ArrayObjIterator_new,\
	hl_types_ArrayObjIterator_hasNext,\
	hl_types_ArrayObjIterator_next,\
	fun$init};
hl_type *hl_functions_types[] = {&t$fun_0cf7b0f,\
	&t$fun_0cf7b0f,\
	&t$fun_2e8f00c,\
	&t$fun_4be1f96,\
	&t$fun_898a634,\
	&t$fun_3321050,\
	&t$fun_3321050,\
	&t$fun_877a08a,\
	&t$fun_c2729d3,\
	&t$fun_c2729d3,\
	&t$fun_0cf7b0f,\
	&t$fun_07a8a5d,\
	&t$fun_07a8a5d,\
	&t$fun_474f12c,\
	&t$fun_735e9b2,\
	&t$fun_431710a,\
	&t$fun_7daa93c,\
	&t$fun_83f90f5,\
	&t$fun_07b476c,\
	&t$fun_07b476c,\
	&t$fun_2e5590a,\
	&t$fun_0b873a8,\
	&t$fun_7180aec,\
	&t$fun_fab01bb,\
	&t$fun_67512d4,\
	&t$fun_d420bf5,\
	&t$fun_9dd8397,\
	&t$fun_ad6559a,\
	&t$fun_7b48b4f,\
	&t$fun_7b48b4f,\
	&t$fun_7b48b4f,\
	&t$fun_7b48b4f,\
	&t$fun_7b48b4f,\
	&t$fun_7b48b4f,\
	&t$fun_7b48b4f,\
	&t$fun_7b48b4f,\
	&t$fun_7b48b4f,\
	&t$fun_7b48b4f,\
	&t$fun_146041c,\
	&t$fun_50a2a57,\
	&t$fun_359a2b1,\
	&t$fun_028fcdb,\
	&t$fun_66dc44f,\
	&t$fun_4a34ed4,\
	&t$fun_9b99f83,\
	&t$fun_1a31d49,\
	&t$fun_e274397,\
	&t$fun_ff5291f,\
	&t$fun_90cc865,\
	&t$fun_8512fa6,\
	&t$fun_a1597d2,\
	&t$fun_ff5291f,\
	&t$fun_cd620e0,\
	&t$fun_05c5c70,\
	&t$fun_273802e,\
	&t$fun_6b8f2f5,\
	&t$fun_649d6d6,\
	&t$fun_4a34ed4,\
	&t$fun_d7336af,\
	&t$fun_d7336af,\
	&t$fun_7874b8f,\
	&t$fun_7874b8f,\
	&t$fun_41dc717,\
	&t$fun_bb9de1f,\
	&t$fun_456327b,\
	&t$fun_2728842,\
	&t$fun_31e3720,\
	&t$fun_66dc44f,\
	&t$fun_e7e1261,\
	&t$fun_90cc865,\
	&t$fun_6a92a5c,\
	&t$fun_887f033,\
	&t$fun_5fd9564,\
	&t$fun_5fd9564,\
	&t$fun_c2d7059,\
	&t$fun_f72790f,\
	&t$fun_e4326cf,\
	&t$fun_e4326cf,\
	&t$fun_8722abf,\
	&t$fun_057735d,\
	&t$fun_5a4a25b,\
	&t$fun_9d4e5fc,\
	&t$fun_d16759d,\
	&t$fun_4eb6a91,\
	&t$fun_4ddc06d,\
	&t$fun_61faa0c,\
	&t$fun_0924a07,\
	&t$fun_6526076,\
	&t$fun_cc3ac55,\
	&t$fun_94ccc5b,\
	&t$fun_e2ad7d5,\
	&t$fun_869b919,\
	&t$fun_e3ed9bc,\
	&t$fun_e0b429b,\
	&t$fun_7d88847,\
	&t$fun_0a33ad9,\
	&t$fun_d3fbc0f,\
	&t$fun_7d88847,\
	&t$fun_d3bd0e8,\
	&t$fun_b188caa,\
	&t$fun_0086861,\
	&t$fun_84e48f9,\
	&t$fun_6d41e68,\
	&t$fun_21e3130,\
	&t$fun_cd61d64,\
	&t$fun_f18ff1f,\
	&t$fun_f18ff1f,\
	&t$fun_33a57e8,\
	&t$fun_33a57e8,\
	&t$fun_7b0f58c,\
	&t$fun_a8827a8,\
	&t$fun_477df90,\
	&t$fun_d666783,\
	&t$fun_e100368,\
	&t$fun_fa4ede4,\
	&t$fun_0220b44,\
	&t$fun_5645aa5,\
	&t$fun_cec3dfe,\
	&t$fun_6c408ca,\
	&t$fun_6c408ca,\
	&t$fun_f1dc20f,\
	&t$fun_5645aa5,\
	&t$fun_628a32f,\
	&t$fun_628a32f,\
	&t$fun_2de193f,\
	&t$fun_fa4ede4,\
	&t$fun_c5f8e15,\
	&t$fun_4f52002,\
	&t$fun_ff2a1e0,\
	&t$fun_657cda2,\
	&t$fun_b7ebdbb,\
	&t$fun_ff2a1e0,\
	&t$fun_a7c0043,\
	&t$fun_1ac3d2f,\
	&t$fun_58500dd,\
	&t$fun_cd6ee2b,\
	&t$fun_0afa491,\
	&t$fun_043889e,\
	&t$fun_cbfbb11,\
	&t$fun_581014c,\
	&t$fun_581014c,\
	&t$fun_7516ce9,\
	&t$fun_7516ce9,\
	&t$fun_b0730e5,\
	&t$fun_6609876,\
	&t$fun_fce9cf4,\
	&t$fun_10f1671,\
	&t$fun_41f7c18,\
	&t$fun_938f64e,\
	&t$fun_e368050,\
	&t$fun_1684400,\
	&t$fun_73888f1,\
	&t$fun_0209fd2,\
	&t$fun_0209fd2,\
	&t$fun_4cc41a0,\
	&t$fun_1684400,\
	&t$fun_fbd527b,\
	&t$fun_fbd527b,\
	&t$fun_2ee88c6,\
	&t$fun_938f64e,\
	&t$fun_90b138e,\
	&t$fun_b237b0e,\
	&t$fun_06eb456,\
	&t$fun_9767ea2,\
	&t$fun_7f2df24,\
	&t$fun_06eb456,\
	&t$fun_46b3fe7,\
	&t$fun_0f6e688,\
	&t$fun_712c9bd,\
	&t$fun_1a69e40,\
	&t$fun_05165e0,\
	&t$fun_1bfe27a,\
	&t$fun_48512d4,\
	&t$fun_3218a3e,\
	&t$fun_3218a3e,\
	&t$fun_bc05abb,\
	&t$fun_bc05abb,\
	&t$fun_d042089,\
	&t$fun_6748920,\
	&t$fun_adaff03,\
	&t$fun_6817c8d,\
	&t$fun_58f9a05,\
	&t$fun_5d217f8,\
	&t$fun_a8583d9,\
	&t$fun_6f78cb5,\
	&t$fun_6324bd7,\
	&t$fun_8f299ff,\
	&t$fun_8f299ff,\
	&t$fun_73d7da9,\
	&t$fun_6f78cb5,\
	&t$fun_779bb7a,\
	&t$fun_779bb7a,\
	&t$fun_0014963,\
	&t$fun_5d217f8,\
	&t$fun_e1c3662,\
	&t$fun_88c3641,\
	&t$fun_79361ea,\
	&t$fun_9ada1e2,\
	&t$fun_25bf129,\
	&t$fun_79361ea,\
	&t$fun_6fe8950,\
	&t$fun_76c9422,\
	&t$fun_bb92de8,\
	&t$fun_2ce2967,\
	&t$fun_ee67120,\
	&t$fun_bc56d4c,\
	&t$fun_7d470df,\
	&t$fun_59cf8ee,\
	&t$fun_59cf8ee,\
	&t$fun_4feb77e,\
	&t$fun_4feb77e,\
	&t$fun_d61d4d0,\
	&t$fun_0f7dabe,\
	&t$fun_98301c5,\
	&t$fun_cf4161f,\
	&t$fun_1e06d39,\
	&t$fun_bc56d4c,\
	&t$fun_c0df3eb,\
	&t$fun_a730fbb,\
	&t$fun_50caa91,\
	&t$fun_fd4a424,\
	&t$fun_fd4a424,\
	&t$fun_e880a67,\
	&t$fun_a730fbb,\
	&t$fun_e35f4e4,\
	&t$fun_e35f4e4,\
	&t$fun_4f1a968,\
	&t$fun_bc56d4c,\
	&t$fun_358bb66,\
	&t$fun_439b121,\
	&t$fun_5daea2a,\
	&t$fun_1bb5e7a,\
	&t$fun_c9b325a,\
	&t$fun_746eb80,\
	&t$fun_ffbcb45,\
	&t$fun_7fbe2c6,\
	&t$fun_715d8bf,\
	&t$fun_ffbcb45,\
	&t$fun_36ccd09,\
	&t$fun_246e7a0,\
	&t$fun_0611c86,\
	&t$fun_3bd7056,\
	&t$fun_0d2ac19,\
	&t$fun_f4509ab,\
	&t$fun_c0b2bf7,\
	&t$fun_c0b2bf7,\
	&t$fun_f334ec9,\
	&t$fun_4052dad,\
	&t$fun_f334ec9,\
	&t$fun_ed49d23,\
	&t$fun_65d82e0,\
	&t$fun_86af97c,\
	&t$fun_2424150,\
	&t$fun_4c2da7d,\
	&t$fun_a163fa2,\
	&t$fun_a163fa2,\
	&t$fun_294d21b,\
	&t$fun_f4509ab,\
	&t$fun_7fbe2c6,\
	&t$fun_ffbcb45,\
	&t$fun_ffbcb45,\
	&t$fun_0d2ac19,\
	&t$fun_f4509ab,\
	&t$fun_c0b2bf7,\
	&t$fun_c0b2bf7,\
	&t$fun_246e7a0,\
	&t$fun_1c0676c,\
	&t$fun_b368daf,\
	&t$fun_352a843,\
	&t$fun_5d45b3d,\
	&t$fun_e670c8f,\
	&t$fun_e670c8f,\
	&t$fun_c079ced,\
	&t$fun_b8dcb1d,\
	&t$fun_e5a2d8d,\
	&t$fun_431ce16,\
	&t$fun_431ce16,\
	&t$fun_0baea77,\
	&t$fun_e5a2d8d,\
	&t$fun_63b98a1,\
	&t$fun_ab25373,\
	&t$fun_a0ea711,\
	&t$fun_8249ca6,\
	&t$fun_9c2ac14,\
	&t$fun_7b48b4f,\
	&t$fun_fab01bb,\
	&t$fun_cb6e3d3,\
	&t$fun_b7334d8,\
	&t$fun_baf777f,\
	&t$fun_e7027a9,\
	&t$fun_1793431,\
	&t$fun_5daea2a,\
	&t$fun_1569556,\
	&t$fun_8bbbd94,\
	&t$fun_75c9212,\
	&t$fun_491b92b,\
	&t$fun_491b92b,\
	&t$fun_f903b64,\
	&t$fun_40779dc,\
	&t$fun_8bbbd94,\
	&t$fun_abea61a,\
	&t$fun_1b2ab6c,\
	&t$fun_b6465b0,\
	&t$fun_e0a06a5,\
	&t$fun_8502ba2,\
	&t$fun_64963c5,\
	&t$fun_2a2b436,\
	&t$fun_fdf49c0,\
	&t$fun_eaaef2e,\
	&t$fun_926956b,\
	&t$fun_b0764ef,\
	&t$fun_544176c,\
	&t$fun_feba9b0,\
	&t$fun_491b92b,\
	&t$fun_0ecc9bc,\
	&t$fun_10aec05,\
	&t$fun_8186749,\
	&t$fun_8186749,\
	&t$fun_17f31ef,\
	&t$fun_95d9f81,\
	&t$fun_8f51bbf,\
	&t$fun_8f51bbf,\
	&t$fun_e1e3de0,\
	&t$fun_ed8c8ee,\
	&t$fun_23e58fc,\
	&t$fun_2b03f8e,\
	&t$fun_b7665f4,\
	&t$fun_715d8bf,\
	&t$fun_2b03f8e,\
	&t$fun_6b7e1eb,\
	&t$fun_0b37ebf,\
	&t$fun_81a6bcb,\
	&t$fun_81a6bcb,\
	&t$fun_3ec66f4,\
	&t$fun_f1e0fdc,\
	&t$fun_06076c9,\
	&t$fun_10909c7,\
	&t$fun_0ecc9bc,\
	&t$fun_06076c9,\
	&t$fun_05c5c70,\
	&t$fun_8245b77,\
	&t$fun_95e430c,\
	&t$fun_8308e1f,\
	&t$fun_21d4cdf,\
	&t$fun_21d4cdf,\
	&t$fun_1ef6dfe,\
	&t$fun_1f02863,\
	&t$fun_be5ea00,\
	&t$fun_4a06caf,\
	&t$fun_99dc1e9,\
	&t$fun_16e5dde,\
	&t$fun_f729cf8,\
	&t$fun_818a08a,\
	&t$fun_818a08a,\
	&t$fun_6c16e15,\
	&t$fun_fd3b467,\
	&t$fun_4c57111,\
	&t$fun_a4d13ad,\
	&t$fun_078836b,\
	&t$fun_e705f35,\
	&t$fun_047f094,\
	&t$fun_62da9da,\
	&t$fun_0efb18a,\
	&t$fun_3aeb07d,\
	&t$fun_3aeb07d,\
	&t$fun_6c047b1,\
	&t$fun_0d9b19a,\
	&t$fun_1793431,\
	&t$fun_0d9b19a,\
	&t$fun_d800c38,\
	&t$fun_cc70830,\
	&t$fun_0d9b19a,\
	&t$fun_10c6fb3,\
	&t$fun_7b48b4f,\
	&t$fun_8186749,\
	&t$fun_99481a7,\
	&t$fun_2533487,\
	&t$fun_ed935ff,\
	&t$fun_ff87c1a,\
	&t$fun_7a5ad5f,\
	&t$fun_5823d1c,\
	&t$fun_1461878,\
	&t$fun_40d3b9d,\
	&t$fun_777d349,\
	&t$fun_e82aa58,\
	&t$fun_f7fbc74,\
	&t$fun_17cbfdc,\
	&t$fun_d3fbc0f,\
	&t$fun_026a163,\
	&t$fun_5138cad,\
	&t$fun_274adf2,\
	&t$fun_b51d32d,\
	&t$fun_cae6940,\
	&t$fun_25bf129,\
	&t$fun_0223e89,\
	&t$fun_d6dbe42,\
	&t$fun_cf72872,\
	&t$fun_064ef4b,\
	&t$fun_3a8cb27,\
	&t$fun_b7ebdbb,\
	&t$fun_56a2bdf,\
	&t$fun_1f6ee54,\
	&t$fun_677a3a6,\
	&t$fun_c880cd2,\
	&t$fun_f66e73a,\
	&t$fun_df79850,\
	&t$fun_7f2df24,\
	&t$fun_f38af0d,\
	&t$fun_3193805,\
	&t$fun_83a2015,\
	&t$fun_c854326,\
	&t$fun_0e7b31e,\
	&t$fun_63e5768,\
	&t$fun_44163b0,\
	&t$fun_622a6a5,\
	&t$fun_0094d0c,\
	&t$fun_8512fa6,\
	&t$fun_2795670,\
	&t$fun_bfddde4,\
	&t$fun_585f248,\
	&t$fun_7b48b4f};

hl__types__ArrayObj hl_types_ArrayObj_alloc(varray* r0) {
	hl__types__ArrayObj r1;
	int r2;
	r1 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	r1->array = r0;
	r2 = r0->size;
	r1->length = r2;
	return r1;
}

void hl_types_ArrayObj_new(hl__types__ArrayObj r0) {
	hl_type *r3;
	varray *r2;
	int r1;
	r1 = 0;
	r0->length = r1;
	r1 = 0;
	r3 = &t$_dyn;
	r2 = hl_alloc_array(r3,r1);
	r0->array = r2;
	return;
}

void hl_types_ArrayBytes_Float_new(hl__types__ArrayBytes_Float r0) {
	vbyte *r2;
	int r1;
	r1 = 0;
	r0->length = r1;
	r0->size = r1;
	r2 = NULL;
	r0->bytes = r2;
	return;
}

void hl_types_ArrayBytes_Int_new(hl__types__ArrayBytes_Int r0) {
	vbyte *r2;
	int r1;
	r1 = 0;
	r0->length = r1;
	r0->size = r1;
	r2 = NULL;
	r0->bytes = r2;
	return;
}

void hl_types_ArrayBytes_hl_F32_new(hl__types__ArrayBytes_hl_F32 r0) {
	vbyte *r2;
	int r1;
	r1 = 0;
	r0->length = r1;
	r0->size = r1;
	r2 = NULL;
	r0->bytes = r2;
	return;
}

void hl_types_ArrayBytes_hl_UI16_new(hl__types__ArrayBytes_hl_UI16 r0) {
	vbyte *r2;
	int r1;
	r1 = 0;
	r0->length = r1;
	r0->size = r1;
	r2 = NULL;
	r0->bytes = r2;
	return;
}

