// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/HlcTestSuite.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
extern $HlcTestSuite g$_HlcTestSuite;
extern haxe__$Log g$_haxe_Log;
extern String s$3e8a55d;
String String___add__(String,String);
extern String s$HlcTestSuite_hx;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$HlcTestSuite;
extern String s$assert;
extern hl_type t$vrt_eaa6a3b;
extern String s$_FAIL_;
extern String s$_Test_Basic_Types_;
extern String s$testBasicTypes;
extern String s$Hello;
extern String s$Integer_value;
extern String s$Float_value;
int String___compare(String,vdynamic*);
extern String s$String_value;
extern String s$Bool_value;
#include <hl/types/ArrayBytes_Int.h>
#include <hl/types/ArrayObj.h>
extern String s$_Test_Arrays_;
extern String s$testArrays;
#include <hl/natives.h>
hl__types__ArrayBytes_Int hl_types_ArrayBase_allocI32(vbyte*,int);
extern String s$Int_array_length;
extern String s$Int_array_access;
extern String s$Int_array_iteration_sum;
extern String s$a;
extern String s$b;
extern String s$c;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern String s$String_array_length;
extern String s$336d5eb;
String hl_types_ArrayObj_join(hl__types__ArrayObj,String);
extern String s$a_b_c;
extern String s$String_array_join;
extern String s$Float_array_length;
int hl_types_ArrayBytes_Int_push(hl__types__ArrayBytes_Int,int);
extern String s$Array_push;
vdynamic* hl_types_ArrayBytes_Int_pop(hl__types__ArrayBytes_Int);
extern String s$Array_pop;
#include <haxe/ds/StringMap.h>
extern String s$_Test_Maps_;
extern String s$testMaps;
extern hl_type t$haxe_ds_StringMap;
void haxe_ds_StringMap_new(haxe__ds__StringMap);
extern String s$one;
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);
extern String s$two;
extern String s$three;
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
extern String s$Map_get;
bool haxe_ds_StringMap_exists(haxe__ds__StringMap,String);
extern String s$Map_exists;
extern String s$four;
extern String s$Map_not_exists;
extern hl_type t$vrt_6b8d1af;
extern hl_type t$fun_eb2fdfb;
extern hl_type t$vrt_0a81a53;
extern hl_type t$fun_bf7849e;
extern hl_type t$fun_820f49a;
extern hl_type t$fun_555f5cd;
extern String s$Map_iteration;
bool haxe_ds_StringMap_remove(haxe__ds__StringMap,String);
extern String s$Map_remove;
extern String s$_Test_Strings_;
extern String s$testStrings;
extern String s$Hello_World_;
extern String s$String_length;
String String_charAt(String,int);
extern String s$H;
extern String s$String_charAt;
extern String s$World;
int String_indexOf(String,String,vdynamic*);
extern String s$String_indexOf;
String String_substr(String,int,vdynamic*);
extern String s$String_substr;
String String_toUpperCase(String);
extern String s$HELLO_WORLD_;
extern String s$String_toUpperCase;
extern String s$fc763cb;
hl__types__ArrayObj String_split(String,String);
extern String s$String_split;
extern String s$String_split_part_0;
extern String s$_Test_Math_;
extern String s$testMath;
extern String s$Math_abs;
double Math_max(double,double);
extern String s$Math_max;
double Math_min(double,double);
extern String s$Math_min;
extern String s$Math_floor;
extern String s$Math_ceil;
extern String s$Math_round;
extern String s$Math_sqrt;
#include <_std/TestPlayer.h>
extern String s$_Test_Classes_;
extern String s$testClasses;
extern hl_type t$TestPlayer;
extern String s$Hero;
void TestPlayer_new(TestPlayer,String,int);
extern String s$Class_field_access;
extern String s$Class_field_value;
void TestPlayer_takeDamage(TestPlayer,int);
extern String s$Class_method_call;
int TestPlayer_heal(TestPlayer,int);
extern String s$Class_method_with_return;
#include <_std/TestGame.h>
extern String s$_Test_Static_Members_;
extern String s$testStaticMembers;
extern $TestGame g$_TestGame;
extern String s$Static_field_initial;
void TestGame_addPoints(int);
extern String s$Static_method_modifies_field;
extern String s$Static_field_accumulation;
int TestGame_getHighScore(void);
extern String s$Static_method_returns_value;
#include <_std/TestState.h>
#include <_std/TestResult.h>
extern String s$_Test_Enums_;
extern String s$testEnums;
extern venum* g$TestState_Running;
extern String s$Enum_value_comparison;
extern venum* g$TestState_Paused;
extern String s$Enum_inequality;
extern hl_type t$TestResult;
extern String s$Enum_with_parameter;
extern String s$Wrong_enum_case;
extern String s$_Test_Exceptions_;
extern String s$testExceptions;
extern String s$Try_block_executed;
extern String s$15152d0;
extern String s$b46ebbb;
extern String s$main;
extern String s$_HLFFI_HLC_Mode_Test_Suite;
extern String s$4c654d8;
extern String s$_Results_;
String String___alloc__(vbyte*,int);
extern String s$ba0629f;
extern String s$_tests_passed;
extern String s$_All_tests_passed_;
extern String s$c8daaa2;
extern String s$_tests_failed;

void HlcTestSuite_assert(bool r0,String r1) {
	vdynobj *r9;
	String r7, r8;
	vvirtual *r10;
	haxe__$Log r6;
	$HlcTestSuite r2;
	vclosure *r5;
	int r3;
	r2 = ($HlcTestSuite)g$_HlcTestSuite;
	r3 = r2->testsRun;
	++r3;
	r2->testsRun = r3;
	if( !r0 ) goto label$61c24ef_1_26;
	r2 = ($HlcTestSuite)g$_HlcTestSuite;
	r3 = r2->testsPassed;
	++r3;
	r2->testsPassed = r3;
	r6 = (haxe__$Log)g$_haxe_Log;
	r5 = r6->trace;
	if( r5 == NULL ) hl_null_access();
	r7 = (String)s$3e8a55d;
	r7 = String___add__(r7,r1);
	r9 = hl_alloc_dynobj();
	r8 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r9,37969014/*fileName*/,&t$String,r8);
	r3 = 16;
	hl_dyn_seti((vdynamic*)r9,371360620/*lineNumber*/,&t$_i32,r3);
	r8 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r9,-63073762/*className*/,&t$String,r8);
	r8 = (String)s$assert;
	hl_dyn_setp((vdynamic*)r9,302979532/*methodName*/,&t$String,r8);
	r10 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r9);
	r5->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r5->fun)((vdynamic*)r5->value,((vdynamic*)r7),r10) : ((void (*)(vdynamic*,vvirtual*))r5->fun)(((vdynamic*)r7),r10);
	goto label$61c24ef_1_42;
	label$61c24ef_1_26:
	r6 = (haxe__$Log)g$_haxe_Log;
	r5 = r6->trace;
	if( r5 == NULL ) hl_null_access();
	r7 = (String)s$_FAIL_;
	r7 = String___add__(r7,r1);
	r9 = hl_alloc_dynobj();
	r8 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r9,37969014/*fileName*/,&t$String,r8);
	r3 = 18;
	hl_dyn_seti((vdynamic*)r9,371360620/*lineNumber*/,&t$_i32,r3);
	r8 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r9,-63073762/*className*/,&t$String,r8);
	r8 = (String)s$assert;
	hl_dyn_setp((vdynamic*)r9,302979532/*methodName*/,&t$String,r8);
	r10 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r9);
	r5->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r5->fun)((vdynamic*)r5->value,((vdynamic*)r7),r10) : ((void (*)(vdynamic*,vvirtual*))r5->fun)(((vdynamic*)r7),r10);
	label$61c24ef_1_42:
	return;
}

void HlcTestSuite_testBasicTypes() {
	vdynobj *r4;
	String r3, r5, r13;
	vvirtual *r7;
	bool r9, r10, r14;
	haxe__$Log r2;
	double r8, r12;
	vclosure *r1;
	int r6, r11;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_Test_Basic_Types_;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 23;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$testBasicTypes;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r6 = 42;
	r8 = 3.1415899999999999;
	r3 = (String)s$Hello;
	r9 = true;
	r11 = 42;
	if( r6 == r11 ) goto label$61c24ef_2_23;
	r10 = false;
	goto label$61c24ef_2_24;
	label$61c24ef_2_23:
	r10 = true;
	label$61c24ef_2_24:
	r5 = (String)s$Integer_value;
	HlcTestSuite_assert(r10,r5);
	r12 = 3.1400000000000001;
	if( !(r12 < r8) ) goto label$61c24ef_2_32;
	r12 = 3.1499999999999999;
	if( !(r8 < r12) ) goto label$61c24ef_2_32;
	r10 = true;
	goto label$61c24ef_2_33;
	label$61c24ef_2_32:
	r10 = false;
	label$61c24ef_2_33:
	r5 = (String)s$Float_value;
	HlcTestSuite_assert(r10,r5);
	r13 = (String)s$Hello;
	if( r3 == r13 || (r3 && r13 && String___compare(r3,(vdynamic*)r13) == 0) ) goto label$61c24ef_2_39;
	r10 = false;
	goto label$61c24ef_2_40;
	label$61c24ef_2_39:
	r10 = true;
	label$61c24ef_2_40:
	r5 = (String)s$String_value;
	HlcTestSuite_assert(r10,r5);
	r14 = true;
	if( r9 == r14 ) goto label$61c24ef_2_46;
	r10 = false;
	goto label$61c24ef_2_47;
	label$61c24ef_2_46:
	r10 = true;
	label$61c24ef_2_47:
	r5 = (String)s$Bool_value;
	HlcTestSuite_assert(r10,r5);
	return;
}

void HlcTestSuite_testArrays() {
	vdynobj *r4;
	String r3, r5;
	hl__types__ArrayObj r14;
	vvirtual *r7;
	hl_type *r16;
	bool r12;
	hl__types__ArrayBytes_Int r8;
	haxe__$Log r2;
	double r17, r18, r19;
	vclosure *r1;
	vdynamic *r20, *r21;
	varray *r15;
	vbyte *r9;
	int r6, r10, r11, r13;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_Test_Arrays_;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 37;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$testArrays;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r6 = 20;
	r9 = hl_alloc_bytes(r6);
	r6 = 0;
	r10 = 1;
	r11 = 2;
	r11 = r6 << r11;
	*(int*)(r9 + r11) = r10;
	++r6;
	r10 = 2;
	r11 = 2;
	r11 = r6 << r11;
	*(int*)(r9 + r11) = r10;
	++r6;
	r10 = 3;
	r11 = 2;
	r11 = r6 << r11;
	*(int*)(r9 + r11) = r10;
	++r6;
	r10 = 4;
	r11 = 2;
	r11 = r6 << r11;
	*(int*)(r9 + r11) = r10;
	++r6;
	r10 = 5;
	r11 = 2;
	r11 = r6 << r11;
	*(int*)(r9 + r11) = r10;
	++r6;
	r6 = 5;
	r8 = hl_types_ArrayBase_allocI32(r9,r6);
	if( r8 == NULL ) hl_null_access();
	r6 = r8->length;
	r10 = 5;
	if( r6 == r10 ) goto label$61c24ef_3_51;
	r12 = false;
	goto label$61c24ef_3_52;
	label$61c24ef_3_51:
	r12 = true;
	label$61c24ef_3_52:
	r3 = (String)s$Int_array_length;
	HlcTestSuite_assert(r12,r3);
	r6 = 0;
	r10 = r8->length;
	if( ((unsigned)r6) < ((unsigned)r10) ) goto label$61c24ef_3_59;
	r6 = 0;
	goto label$61c24ef_3_63;
	label$61c24ef_3_59:
	r9 = r8->bytes;
	r10 = 2;
	r10 = r6 << r10;
	r6 = *(int*)(r9 + r10);
	label$61c24ef_3_63:
	r10 = 1;
	if( r6 == r10 ) goto label$61c24ef_3_67;
	r12 = false;
	goto label$61c24ef_3_68;
	label$61c24ef_3_67:
	r12 = true;
	label$61c24ef_3_68:
	r3 = (String)s$Int_array_access;
	HlcTestSuite_assert(r12,r3);
	r6 = 0;
	r10 = 0;
	label$61c24ef_3_72:
	if( r8 == NULL ) hl_null_access();
	r13 = r8->length;
	if( r10 >= r13 ) goto label$61c24ef_3_88;
	r13 = r8->length;
	if( ((unsigned)r10) < ((unsigned)r13) ) goto label$61c24ef_3_80;
	r11 = 0;
	goto label$61c24ef_3_84;
	label$61c24ef_3_80:
	r9 = r8->bytes;
	r13 = 2;
	r13 = r10 << r13;
	r11 = *(int*)(r9 + r13);
	label$61c24ef_3_84:
	++r10;
	r13 = r6 + r11;
	r6 = r13;
	goto label$61c24ef_3_72;
	label$61c24ef_3_88:
	r11 = 15;
	if( r6 == r11 ) goto label$61c24ef_3_92;
	r12 = false;
	goto label$61c24ef_3_93;
	label$61c24ef_3_92:
	r12 = true;
	label$61c24ef_3_93:
	r3 = (String)s$Int_array_iteration_sum;
	HlcTestSuite_assert(r12,r3);
	r16 = &t$String;
	r10 = 3;
	r15 = hl_alloc_array(r16,r10);
	r3 = (String)s$a;
	r10 = 0;
	((String*)(r15 + 1))[r10] = r3;
	r3 = (String)s$b;
	r10 = 1;
	((String*)(r15 + 1))[r10] = r3;
	r3 = (String)s$c;
	r10 = 2;
	((String*)(r15 + 1))[r10] = r3;
	r14 = hl_types_ArrayObj_alloc(r15);
	if( r14 == NULL ) hl_null_access();
	r10 = r14->length;
	r11 = 3;
	if( r10 == r11 ) goto label$61c24ef_3_114;
	r12 = false;
	goto label$61c24ef_3_115;
	label$61c24ef_3_114:
	r12 = true;
	label$61c24ef_3_115:
	r3 = (String)s$String_array_length;
	HlcTestSuite_assert(r12,r3);
	r3 = (String)s$336d5eb;
	r3 = hl_types_ArrayObj_join(r14,r3);
	r5 = (String)s$a_b_c;
	if( r3 == r5 || (r3 && r5 && String___compare(r3,(vdynamic*)r5) == 0) ) goto label$61c24ef_3_123;
	r12 = false;
	goto label$61c24ef_3_124;
	label$61c24ef_3_123:
	r12 = true;
	label$61c24ef_3_124:
	r3 = (String)s$String_array_join;
	HlcTestSuite_assert(r12,r3);
	r17 = 1.1000000000000001;
	r18 = 2.2000000000000002;
	r19 = 3.2999999999999998;
	r12 = true;
	r3 = (String)s$Float_array_length;
	HlcTestSuite_assert(r12,r3);
	r10 = 6;
	r10 = hl_types_ArrayBytes_Int_push(r8,r10);
	r10 = r8->length;
	r11 = 6;
	if( r10 == r11 ) goto label$61c24ef_3_139;
	r12 = false;
	goto label$61c24ef_3_140;
	label$61c24ef_3_139:
	r12 = true;
	label$61c24ef_3_140:
	r3 = (String)s$Array_push;
	HlcTestSuite_assert(r12,r3);
	r20 = hl_types_ArrayBytes_Int_pop(r8);
	r10 = 6;
	r21 = hl_alloc_dynamic(&t$_i32);
	r21->v.i = r10;
	if( r20 == r21 || (r20 && r21 && (r20->v.i == r21->v.i)) ) goto label$61c24ef_3_148;
	r12 = false;
	goto label$61c24ef_3_149;
	label$61c24ef_3_148:
	r12 = true;
	label$61c24ef_3_149:
	r3 = (String)s$Array_pop;
	HlcTestSuite_assert(r12,r3);
	return;
}

void HlcTestSuite_testMaps() {
	vdynobj *r4;
	String r3, r5;
	haxe__ds__StringMap r8;
	vvirtual *r7, *r13, *r14, *r15, *r16;
	bool r10;
	haxe__$Log r2;
	vclosure *r1;
	vdynamic *r9, *r11, *r12;
	int r6, r17, r18;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_Test_Maps_;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 60;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$testMaps;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r8 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r8);
	r3 = (String)s$one;
	r6 = 1;
	r9 = hl_alloc_dynamic(&t$_i32);
	r9->v.i = r6;
	haxe_ds_StringMap_set(r8,r3,((vdynamic*)r9));
	r3 = (String)s$two;
	r6 = 2;
	r9 = hl_alloc_dynamic(&t$_i32);
	r9->v.i = r6;
	haxe_ds_StringMap_set(r8,r3,((vdynamic*)r9));
	r3 = (String)s$three;
	r6 = 3;
	r9 = hl_alloc_dynamic(&t$_i32);
	r9->v.i = r6;
	haxe_ds_StringMap_set(r8,r3,((vdynamic*)r9));
	r3 = (String)s$one;
	r11 = haxe_ds_StringMap_get(r8,r3);
	r9 = (vdynamic*)r11;
	r6 = 1;
	r12 = hl_alloc_dynamic(&t$_i32);
	r12->v.i = r6;
	if( r9 == r12 || (r9 && r12 && (r9->v.i == r12->v.i)) ) goto label$61c24ef_4_37;
	r10 = false;
	goto label$61c24ef_4_38;
	label$61c24ef_4_37:
	r10 = true;
	label$61c24ef_4_38:
	r3 = (String)s$Map_get;
	HlcTestSuite_assert(r10,r3);
	r3 = (String)s$two;
	r10 = haxe_ds_StringMap_exists(r8,r3);
	r3 = (String)s$Map_exists;
	HlcTestSuite_assert(r10,r3);
	r3 = (String)s$four;
	r10 = haxe_ds_StringMap_exists(r8,r3);
	r10 = !r10;
	r3 = (String)s$Map_not_exists;
	HlcTestSuite_assert(r10,r3);
	r6 = 0;
	if( r8 ) goto label$61c24ef_4_53;
	r13 = NULL;
	goto label$61c24ef_4_57;
	label$61c24ef_4_53:
	r13 = r8->f$1;
	if( r13 ) goto label$61c24ef_4_57;
	r13 = hl_to_virtual(&t$vrt_6b8d1af,(vdynamic*)r8);
	r8->f$1 = r13;
	label$61c24ef_4_57:
	r14 = r13;
	if( r13 == NULL ) hl_null_access();
	if( hl_vfields(r13)[0] ) r15 = ((vvirtual* (*)(vdynamic*))hl_vfields(r13)[0])(r13->value); else {
		r15 = (vvirtual*)hl_dyn_call_obj(r13->value,&t$fun_eb2fdfb,117891838/*keys*/,NULL,NULL);
	}
	r16 = hl_to_virtual(&t$vrt_0a81a53,(vdynamic*)r15);
	label$61c24ef_4_61:
	if( r16 == NULL ) hl_null_access();
	if( hl_vfields(r16)[0] ) r10 = ((bool (*)(vdynamic*))hl_vfields(r16)[0])(r16->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r16->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r10 = (bool)ret.v.i;
	}
	if( !r10 ) goto label$61c24ef_4_72;
	if( hl_vfields(r16)[1] ) r3 = ((String (*)(vdynamic*))hl_vfields(r16)[1])(r16->value); else {
		r3 = (String)hl_dyn_call_obj(r16->value,&t$fun_820f49a,151160317/*next*/,NULL,NULL);
	}
	if( r14 == NULL ) hl_null_access();
	if( hl_vfields(r14)[1] ) r11 = ((vdynamic* (*)(vdynamic*,String))hl_vfields(r14)[1])(r14->value,r3); else {
		void *args[] = {r3};
		r11 = (vdynamic*)hl_dyn_call_obj(r14->value,&t$fun_555f5cd,5144726/*get*/,args,NULL);
	}
	r9 = (vdynamic*)r11;
	r17 = r9 ? r9->v.i : 0;
	++r6;
	goto label$61c24ef_4_61;
	label$61c24ef_4_72:
	r18 = 3;
	if( r6 == r18 ) goto label$61c24ef_4_76;
	r10 = false;
	goto label$61c24ef_4_77;
	label$61c24ef_4_76:
	r10 = true;
	label$61c24ef_4_77:
	r3 = (String)s$Map_iteration;
	HlcTestSuite_assert(r10,r3);
	if( r8 == NULL ) hl_null_access();
	r3 = (String)s$two;
	r10 = haxe_ds_StringMap_remove(r8,r3);
	r3 = (String)s$two;
	r10 = haxe_ds_StringMap_exists(r8,r3);
	r10 = !r10;
	r3 = (String)s$Map_remove;
	HlcTestSuite_assert(r10,r3);
	return;
}

void HlcTestSuite_testStrings() {
	vdynobj *r4;
	String r3, r5, r10;
	hl__types__ArrayObj r12;
	vvirtual *r7;
	bool r8;
	haxe__$Log r2;
	vclosure *r1;
	vdynamic *r11, *r13;
	varray *r14;
	int r6, r9;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_Test_Strings_;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 80;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$testStrings;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r3 = (String)s$Hello_World_;
	if( r3 == NULL ) hl_null_access();
	r6 = r3->length;
	r9 = 13;
	if( r6 == r9 ) goto label$61c24ef_5_22;
	r8 = false;
	goto label$61c24ef_5_23;
	label$61c24ef_5_22:
	r8 = true;
	label$61c24ef_5_23:
	r5 = (String)s$String_length;
	HlcTestSuite_assert(r8,r5);
	r6 = 0;
	r5 = String_charAt(r3,r6);
	r10 = (String)s$H;
	if( r5 == r10 || (r5 && r10 && String___compare(r5,(vdynamic*)r10) == 0) ) goto label$61c24ef_5_31;
	r8 = false;
	goto label$61c24ef_5_32;
	label$61c24ef_5_31:
	r8 = true;
	label$61c24ef_5_32:
	r5 = (String)s$String_charAt;
	HlcTestSuite_assert(r8,r5);
	r10 = (String)s$World;
	r11 = NULL;
	r6 = String_indexOf(r3,r10,r11);
	r9 = 7;
	if( r6 == r9 ) goto label$61c24ef_5_41;
	r8 = false;
	goto label$61c24ef_5_42;
	label$61c24ef_5_41:
	r8 = true;
	label$61c24ef_5_42:
	r5 = (String)s$String_indexOf;
	HlcTestSuite_assert(r8,r5);
	r6 = 0;
	r9 = 5;
	r11 = hl_alloc_dynamic(&t$_i32);
	r11->v.i = r9;
	r5 = String_substr(r3,r6,r11);
	r10 = (String)s$Hello;
	if( r5 == r10 || (r5 && r10 && String___compare(r5,(vdynamic*)r10) == 0) ) goto label$61c24ef_5_52;
	r8 = false;
	goto label$61c24ef_5_53;
	label$61c24ef_5_52:
	r8 = true;
	label$61c24ef_5_53:
	r5 = (String)s$String_substr;
	HlcTestSuite_assert(r8,r5);
	r5 = String_toUpperCase(r3);
	r10 = (String)s$HELLO_WORLD_;
	if( r5 == r10 || (r5 && r10 && String___compare(r5,(vdynamic*)r10) == 0) ) goto label$61c24ef_5_60;
	r8 = false;
	goto label$61c24ef_5_61;
	label$61c24ef_5_60:
	r8 = true;
	label$61c24ef_5_61:
	r5 = (String)s$String_toUpperCase;
	HlcTestSuite_assert(r8,r5);
	r10 = (String)s$fc763cb;
	r12 = String_split(r3,r10);
	if( r12 == NULL ) hl_null_access();
	r6 = r12->length;
	r9 = 2;
	if( r6 == r9 ) goto label$61c24ef_5_71;
	r8 = false;
	goto label$61c24ef_5_72;
	label$61c24ef_5_71:
	r8 = true;
	label$61c24ef_5_72:
	r5 = (String)s$String_split;
	HlcTestSuite_assert(r8,r5);
	r6 = 0;
	r9 = r12->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$61c24ef_5_79;
	r5 = NULL;
	goto label$61c24ef_5_82;
	label$61c24ef_5_79:
	r14 = r12->array;
	r13 = ((vdynamic**)(r14 + 1))[r6];
	r5 = (String)r13;
	label$61c24ef_5_82:
	r10 = (String)s$Hello;
	if( r5 == r10 || (r5 && r10 && String___compare(r5,(vdynamic*)r10) == 0) ) goto label$61c24ef_5_86;
	r8 = false;
	goto label$61c24ef_5_87;
	label$61c24ef_5_86:
	r8 = true;
	label$61c24ef_5_87:
	r5 = (String)s$String_split_part_0;
	HlcTestSuite_assert(r8,r5);
	return;
}

void HlcTestSuite_testMath() {
	vdynobj *r4;
	String r3, r5;
	vvirtual *r7;
	bool r8;
	haxe__$Log r2;
	double r9, r10;
	vclosure *r1;
	int r6, r11;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_Test_Math_;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 95;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$testMath;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r9 = -5.;
	r9 = hl_math_abs(r9);
	r10 = 5.;
	if( r9 == r10 ) goto label$61c24ef_6_21;
	r8 = false;
	goto label$61c24ef_6_22;
	label$61c24ef_6_21:
	r8 = true;
	label$61c24ef_6_22:
	r3 = (String)s$Math_abs;
	HlcTestSuite_assert(r8,r3);
	r9 = 3.;
	r10 = 7.;
	r9 = Math_max(r9,r10);
	r10 = 7.;
	if( r9 == r10 ) goto label$61c24ef_6_31;
	r8 = false;
	goto label$61c24ef_6_32;
	label$61c24ef_6_31:
	r8 = true;
	label$61c24ef_6_32:
	r3 = (String)s$Math_max;
	HlcTestSuite_assert(r8,r3);
	r9 = 3.;
	r10 = 7.;
	r9 = Math_min(r9,r10);
	r10 = 3.;
	if( r9 == r10 ) goto label$61c24ef_6_41;
	r8 = false;
	goto label$61c24ef_6_42;
	label$61c24ef_6_41:
	r8 = true;
	label$61c24ef_6_42:
	r3 = (String)s$Math_min;
	HlcTestSuite_assert(r8,r3);
	r8 = true;
	r3 = (String)s$Math_floor;
	HlcTestSuite_assert(r8,r3);
	r8 = true;
	r3 = (String)s$Math_ceil;
	HlcTestSuite_assert(r8,r3);
	r9 = 3.5;
	r6 = hl_math_round(r9);
	r11 = 4;
	if( r6 == r11 ) goto label$61c24ef_6_56;
	r8 = false;
	goto label$61c24ef_6_57;
	label$61c24ef_6_56:
	r8 = true;
	label$61c24ef_6_57:
	r3 = (String)s$Math_round;
	HlcTestSuite_assert(r8,r3);
	r9 = 16.;
	r9 = hl_math_sqrt(r9);
	r10 = 4.;
	if( r9 == r10 ) goto label$61c24ef_6_65;
	r8 = false;
	goto label$61c24ef_6_66;
	label$61c24ef_6_65:
	r8 = true;
	label$61c24ef_6_66:
	r3 = (String)s$Math_sqrt;
	HlcTestSuite_assert(r8,r3);
	return;
}

void HlcTestSuite_testClasses() {
	vdynobj *r4;
	String r3, r5;
	TestPlayer r8;
	vvirtual *r7;
	bool r9;
	haxe__$Log r2;
	vclosure *r1;
	int r6, r10;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_Test_Classes_;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 107;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$testClasses;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r8 = (TestPlayer)hl_alloc_obj(&t$TestPlayer);
	r3 = (String)s$Hero;
	r6 = 100;
	TestPlayer_new(r8,r3,r6);
	r3 = r8->name;
	r5 = (String)s$Hero;
	if( r3 == r5 || (r3 && r5 && String___compare(r3,(vdynamic*)r5) == 0) ) goto label$61c24ef_7_24;
	r9 = false;
	goto label$61c24ef_7_25;
	label$61c24ef_7_24:
	r9 = true;
	label$61c24ef_7_25:
	r3 = (String)s$Class_field_access;
	HlcTestSuite_assert(r9,r3);
	r6 = r8->health;
	r10 = 100;
	if( r6 == r10 ) goto label$61c24ef_7_32;
	r9 = false;
	goto label$61c24ef_7_33;
	label$61c24ef_7_32:
	r9 = true;
	label$61c24ef_7_33:
	r3 = (String)s$Class_field_value;
	HlcTestSuite_assert(r9,r3);
	r6 = 30;
	TestPlayer_takeDamage(r8,r6);
	r6 = r8->health;
	r10 = 70;
	if( r6 == r10 ) goto label$61c24ef_7_42;
	r9 = false;
	goto label$61c24ef_7_43;
	label$61c24ef_7_42:
	r9 = true;
	label$61c24ef_7_43:
	r3 = (String)s$Class_method_call;
	HlcTestSuite_assert(r9,r3);
	r6 = 20;
	r6 = TestPlayer_heal(r8,r6);
	r6 = r8->health;
	r10 = 90;
	if( r6 == r10 ) goto label$61c24ef_7_52;
	r9 = false;
	goto label$61c24ef_7_53;
	label$61c24ef_7_52:
	r9 = true;
	label$61c24ef_7_53:
	r3 = (String)s$Class_method_with_return;
	HlcTestSuite_assert(r9,r3);
	return;
}

void HlcTestSuite_testStaticMembers() {
	vdynobj *r4;
	String r3, r5;
	$TestGame r8;
	vvirtual *r7;
	bool r9;
	haxe__$Log r2;
	vclosure *r1;
	int r6, r10;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_Test_Static_Members_;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 121;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$testStaticMembers;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r6 = 0;
	r8 = ($TestGame)g$_TestGame;
	r8->score = r6;
	r8 = ($TestGame)g$_TestGame;
	r6 = r8->score;
	r10 = 0;
	if( r6 == r10 ) goto label$61c24ef_8_24;
	r9 = false;
	goto label$61c24ef_8_25;
	label$61c24ef_8_24:
	r9 = true;
	label$61c24ef_8_25:
	r3 = (String)s$Static_field_initial;
	HlcTestSuite_assert(r9,r3);
	r6 = 100;
	TestGame_addPoints(r6);
	r8 = ($TestGame)g$_TestGame;
	r6 = r8->score;
	r10 = 100;
	if( r6 == r10 ) goto label$61c24ef_8_35;
	r9 = false;
	goto label$61c24ef_8_36;
	label$61c24ef_8_35:
	r9 = true;
	label$61c24ef_8_36:
	r3 = (String)s$Static_method_modifies_field;
	HlcTestSuite_assert(r9,r3);
	r6 = 50;
	TestGame_addPoints(r6);
	r8 = ($TestGame)g$_TestGame;
	r6 = r8->score;
	r10 = 150;
	if( r6 == r10 ) goto label$61c24ef_8_46;
	r9 = false;
	goto label$61c24ef_8_47;
	label$61c24ef_8_46:
	r9 = true;
	label$61c24ef_8_47:
	r3 = (String)s$Static_field_accumulation;
	HlcTestSuite_assert(r9,r3);
	r6 = TestGame_getHighScore();
	r10 = 150;
	if( r6 == r10 ) goto label$61c24ef_8_54;
	r9 = false;
	goto label$61c24ef_8_55;
	label$61c24ef_8_54:
	r9 = true;
	label$61c24ef_8_55:
	r3 = (String)s$Static_method_returns_value;
	HlcTestSuite_assert(r9,r3);
	return;
}

void HlcTestSuite_testEnums() {
	vdynobj *r4;
	String r3, r5;
	vvirtual *r7;
	venum *r8, *r10, *r11, *r12;
	bool r9;
	haxe__$Log r2;
	vclosure *r1;
	int r6, r13;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_Test_Enums_;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 136;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$testEnums;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r8 = (venum*)g$TestState_Running;
	r11 = (venum*)g$TestState_Running;
	if( r8 == r11 ) goto label$61c24ef_9_20;
	r9 = false;
	goto label$61c24ef_9_21;
	label$61c24ef_9_20:
	r9 = true;
	label$61c24ef_9_21:
	r3 = (String)s$Enum_value_comparison;
	HlcTestSuite_assert(r9,r3);
	r10 = (venum*)g$TestState_Paused;
	r11 = (venum*)g$TestState_Running;
	if( r10 != r11 ) goto label$61c24ef_9_28;
	r9 = false;
	goto label$61c24ef_9_29;
	label$61c24ef_9_28:
	r9 = true;
	label$61c24ef_9_29:
	r3 = (String)s$Enum_inequality;
	HlcTestSuite_assert(r9,r3);
	r6 = 42;
	r12 = hl_alloc_enum(&t$TestResult,0);
	((TestResult_Success*)r12)->p0 = r6;
	if( r12 == NULL ) hl_null_access();
	r6 = HL__ENUM_INDEX__(r12);
	switch(r6) {
		default:
			goto label$61c24ef_9_50;
		case 0:
			r6 = ((TestResult_Success*)r12)->p0;
			r13 = 42;
			if( r6 == r13 ) goto label$61c24ef_9_42;
			r9 = false;
			goto label$61c24ef_9_43;
			label$61c24ef_9_42:
			r9 = true;
			label$61c24ef_9_43:
			r3 = (String)s$Enum_with_parameter;
			HlcTestSuite_assert(r9,r3);
			goto label$61c24ef_9_50;
		case 1:
			r3 = ((TestResult_Error*)r12)->p0;
			r9 = false;
			r5 = (String)s$Wrong_enum_case;
			HlcTestSuite_assert(r9,r5);
	}
	label$61c24ef_9_50:
	return;
}

void HlcTestSuite_testExceptions() {
	vdynobj *r4;
	String r3, r5;
	vvirtual *r7;
	bool r11;
	haxe__$Log r2;
	vclosure *r1;
	vdynamic *r8, *r10;
	int r6, r9, r12;
	hl_trap_ctx trap$0;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_Test_Exceptions_;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 154;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$testExceptions;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r6 = 0;
	hl_trap(trap$0,r8,label$61c24ef_10_20);
	r9 = 42;
	hl_endtrap(trap$0);
	goto label$61c24ef_10_22;
	label$61c24ef_10_20:
	r10 = NULL;
	r9 = -1;
	label$61c24ef_10_22:
	r12 = 42;
	if( r9 == r12 ) goto label$61c24ef_10_26;
	r11 = false;
	goto label$61c24ef_10_27;
	label$61c24ef_10_26:
	r11 = true;
	label$61c24ef_10_27:
	r3 = (String)s$Try_block_executed;
	HlcTestSuite_assert(r11,r3);
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$15152d0;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r9 = 164;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r9);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$testExceptions;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	return;
}

void HlcTestSuite_main() {
	vdynobj *r4;
	String r3, r5;
	vvirtual *r7;
	haxe__$Log r2;
	$HlcTestSuite r8;
	vclosure *r1;
	int *r9;
	vbyte *r10;
	int r6, r11;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$b46ebbb;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 168;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_HLFFI_HLC_Mode_Test_Suite;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 169;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$b46ebbb;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 170;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	HlcTestSuite_testBasicTypes();
	HlcTestSuite_testArrays();
	HlcTestSuite_testMaps();
	HlcTestSuite_testStrings();
	HlcTestSuite_testMath();
	HlcTestSuite_testClasses();
	HlcTestSuite_testStaticMembers();
	HlcTestSuite_testEnums();
	HlcTestSuite_testExceptions();
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$4c654d8;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 182;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_Results_;
	r8 = ($HlcTestSuite)g$_HlcTestSuite;
	r6 = r8->testsPassed;
	r9 = &r6;
	r10 = hl_itos(r6,r9);
	r5 = String___alloc__(r10,r6);
	r3 = String___add__(r3,r5);
	r5 = (String)s$ba0629f;
	r3 = String___add__(r3,r5);
	r8 = ($HlcTestSuite)g$_HlcTestSuite;
	r6 = r8->testsRun;
	r9 = &r6;
	r10 = hl_itos(r6,r9);
	r5 = String___alloc__(r10,r6);
	r3 = String___add__(r3,r5);
	r5 = (String)s$_tests_passed;
	r3 = String___add__(r3,r5);
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 183;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r8 = ($HlcTestSuite)g$_HlcTestSuite;
	r6 = r8->testsPassed;
	r8 = ($HlcTestSuite)g$_HlcTestSuite;
	r11 = r8->testsRun;
	if( r6 != r11 ) goto label$61c24ef_11_121;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$_All_tests_passed_;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 185;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	goto label$61c24ef_11_147;
	label$61c24ef_11_121:
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$c8daaa2;
	r8 = ($HlcTestSuite)g$_HlcTestSuite;
	r6 = r8->testsRun;
	r8 = ($HlcTestSuite)g$_HlcTestSuite;
	r11 = r8->testsPassed;
	r6 = r6 - r11;
	r9 = &r6;
	r10 = hl_itos(r6,r9);
	r5 = String___alloc__(r10,r6);
	r3 = String___add__(r3,r5);
	r5 = (String)s$_tests_failed;
	r3 = String___add__(r3,r5);
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 187;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	label$61c24ef_11_147:
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$b46ebbb;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HlcTestSuite_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 189;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HlcTestSuite;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	return;
}

