// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__HlcTestSuite
#define INC__std__HlcTestSuite
typedef struct _$HlcTestSuite *$HlcTestSuite;
typedef struct _HlcTestSuite *HlcTestSuite;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _$HlcTestSuite {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	int testsRun;
	int testsPassed;
	vclosure* assert;
	vclosure* testBasicTypes;
	vclosure* testArrays;
	vclosure* testMaps;
	vclosure* testStrings;
	vclosure* testMath;
	vclosure* testClasses;
	vclosure* testStaticMembers;
	vclosure* testEnums;
	vclosure* testExceptions;
	vclosure* main;
};
struct _HlcTestSuite {
	hl_type *$type;
};
#endif

