// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/Std.h>
#include <hl/natives.h>
extern hl_type t$String;
extern hl_type t$_dyn;
String String___add__(String,String);
extern hl_type t$_f64;
extern hl_type t$_i32;
extern String s$Can_t_add_;
extern String s$84c4047;
extern hl_type t$_type;
extern String s$_and_;
extern String s$9371d7a;

String Std_string(vdynamic* r0) {
	String r4;
	int *r3;
	vbyte *r2;
	int r1;
	r1 = 0;
	r3 = &r1;
	r2 = hl_value_to_string(r0,r3);
	r4 = (String)hl_alloc_obj(&t$String);
	r4->bytes = r2;
	r4->length = r1;
	return r4;
}

vdynamic* Std___add__(vdynamic* r0,vdynamic* r1) {
	String r6, r7;
	hl_type *r2, *r4, *r5;
	double r9, r12, r13;
	vdynamic *r3;
	int r8, r10, r11;
	r2 = r0 ? ((vdynamic*)r0)->t : &hlt_void;
	r4 = r1 ? ((vdynamic*)r1)->t : &hlt_void;
	r5 = &t$String;
	if( hl_same_type(r2,r5) != 0 ) {} else goto label$5427174_2_8;
	r6 = (String)hl_dyn_castp(&r0,&t$_dyn,&t$String);
	r7 = Std_string(r1);
	r6 = String___add__(r6,r7);
	return ((vdynamic*)r6);
	label$5427174_2_8:
	r5 = &t$String;
	if( hl_same_type(r4,r5) != 0 ) {} else goto label$5427174_2_14;
	r6 = Std_string(r0);
	r7 = (String)hl_dyn_castp(&r1,&t$_dyn,&t$String);
	r6 = String___add__(r6,r7);
	return ((vdynamic*)r6);
	label$5427174_2_14:
	r8 = r2->kind;
	switch(r8) {
		default:
		case 4:
			goto label$5427174_2_56;
		case 0:
			r8 = r4->kind;
			switch(r8) {
				default:
				case 4:
					goto label$5427174_2_24;
				case 0:
					r9 = 0.;
					r3 = hl_alloc_dynamic(&t$_f64);
					r3->v.d = r9;
					return r3;
				case 1:
				case 2:
				case 3:
				case 5:
				case 6:
					return r1;
			}
			label$5427174_2_24:
			goto label$5427174_2_56;
		case 1:
		case 2:
		case 3:
			r8 = (int)hl_dyn_casti(&r0,&t$_dyn,&t$_i32);
			r10 = r4->kind;
			switch(r10) {
				default:
				case 4:
					goto label$5427174_2_40;
				case 0:
					r3 = hl_alloc_dynamic(&t$_i32);
					r3->v.i = r8;
					return r3;
				case 1:
				case 2:
				case 3:
					r11 = (int)hl_dyn_casti(&r1,&t$_dyn,&t$_i32);
					r10 = r8 + r11;
					r3 = hl_alloc_dynamic(&t$_i32);
					r3->v.i = r10;
					return r3;
				case 5:
				case 6:
					r9 = (double)r8;
					r12 = (double)hl_dyn_castd(&r1,&t$_dyn);
					r9 = r9 + r12;
					r3 = hl_alloc_dynamic(&t$_f64);
					r3->v.d = r9;
					return r3;
			}
			label$5427174_2_40:
			goto label$5427174_2_56;
		case 5:
		case 6:
			r9 = (double)hl_dyn_castd(&r0,&t$_dyn);
			r8 = r4->kind;
			switch(r8) {
				default:
				case 4:
					goto label$5427174_2_56;
				case 0:
					r3 = hl_alloc_dynamic(&t$_f64);
					r3->v.d = r9;
					return r3;
				case 1:
				case 2:
				case 3:
					r8 = (int)hl_dyn_casti(&r1,&t$_dyn,&t$_i32);
					r13 = (double)r8;
					r12 = r9 + r13;
					r3 = hl_alloc_dynamic(&t$_f64);
					r3->v.d = r12;
					return r3;
				case 5:
				case 6:
					r13 = (double)hl_dyn_castd(&r1,&t$_dyn);
					r12 = r9 + r13;
					r3 = hl_alloc_dynamic(&t$_f64);
					r3->v.d = r12;
					return r3;
			}
	}
	label$5427174_2_56:
	r6 = (String)s$Can_t_add_;
	r7 = Std_string(r0);
	r6 = String___add__(r6,r7);
	r7 = (String)s$84c4047;
	r6 = String___add__(r6,r7);
	if( r2 == NULL ) r3 = NULL; else {
		r3 = hl_alloc_dynamic(&t$_type);
		r3->v.ptr = r2;
	}
	r7 = Std_string(r3);
	r6 = String___add__(r6,r7);
	r7 = (String)s$_and_;
	r6 = String___add__(r6,r7);
	r7 = Std_string(r1);
	r6 = String___add__(r6,r7);
	r7 = (String)s$84c4047;
	r6 = String___add__(r6,r7);
	if( r4 == NULL ) r3 = NULL; else {
		r3 = hl_alloc_dynamic(&t$_type);
		r3->v.ptr = r4;
	}
	r7 = Std_string(r3);
	r6 = String___add__(r6,r7);
	r7 = (String)s$9371d7a;
	r6 = String___add__(r6,r7);
	hl_throw((vdynamic*)r6);
}

