// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/TestGame.h>
extern $TestGame g$_TestGame;

void TestGame_addPoints(int r0) {
	$TestGame r1;
	int r2, r3;
	r1 = ($TestGame)g$_TestGame;
	r2 = r1->score;
	r2 = r2 + r0;
	r1->score = r2;
	r1 = ($TestGame)g$_TestGame;
	r2 = r1->score;
	r1 = ($TestGame)g$_TestGame;
	r3 = r1->highScore;
	if( r3 >= r2 ) goto label$f74833a_1_13;
	r1 = ($TestGame)g$_TestGame;
	r2 = r1->score;
	r1 = ($TestGame)g$_TestGame;
	r1->highScore = r2;
	label$f74833a_1_13:
	return;
}

int TestGame_getHighScore() {
	$TestGame r1;
	int r0;
	r1 = ($TestGame)g$_TestGame;
	r0 = r1->highScore;
	return r0;
}

void TestGame_reset() {
	$TestGame r1;
	int r0;
	r0 = 0;
	r1 = ($TestGame)g$_TestGame;
	r1->score = r0;
	return;
}

