// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__TestGame
#define INC__std__TestGame
typedef struct _$TestGame *$TestGame;
typedef struct _TestGame *TestGame;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _$TestGame {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	int score;
	int highScore;
	vclosure* addPoints;
	vclosure* getHighScore;
	vclosure* reset;
};
struct _TestGame {
	hl_type *$type;
};
#endif

