// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__TestResult
#define INC__std__TestResult
typedef struct _$TestResult *$TestResult;
#include <hl/Enum.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>
#include <_std/TestResult.h>


struct _$TestResult {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___ename__;
	hl_bytes_map* _hx___emap__;
	hl__types__ArrayObj _hx___constructs__;
	varray* _hx___evalues__;
};
typedef struct {
	HL__ENUM_CONSTRUCT__
	int p0;
} TestResult_Success;
typedef struct {
	HL__ENUM_CONSTRUCT__
	String p0;
} TestResult_Error;
#endif

