// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/TestPlayer.h>

void TestPlayer_new(TestPlayer r0,String r1,int r2) {
	r0->name = r1;
	r0->health = r2;
	return;
}

void TestPlayer_takeDamage(TestPlayer r0,int r1) {
	int r2, r3;
	r2 = r0->health;
	r2 = r2 - r1;
	r0->health = r2;
	r2 = r0->health;
	r3 = 0;
	if( r2 >= r3 ) goto label$f6fd7b6_2_8;
	r2 = 0;
	r0->health = r2;
	label$f6fd7b6_2_8:
	return;
}

int TestPlayer_heal(TestPlayer r0,int r1) {
	int r2;
	r2 = r0->health;
	r2 = r2 + r1;
	r0->health = r2;
	r2 = r0->health;
	return r2;
}

