// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__Type
#define INC__std__Type
typedef struct _$Type *$Type;
typedef struct _Type *Type;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/Enum.h>


struct _$Type {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* init;
	vclosure* initClass;
	vclosure* initEnum;
	vclosure* _hx_register;
};
struct _Type {
	hl_type *$type;
};
#endif

