// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/Type.h>
#include <hl/natives.h>
extern hl_bytes_map* g$__types__;
extern hl_type t$hl_Class;
extern hl_type t$_dyn;
extern hl_type t$String;
void Type_register(vbyte*,hl__BaseType);
#include <hl/types/ArrayObj.h>
extern hl_type t$hl_Enum;
extern hl_type t$hl_types_ArrayObj;
void hl_types_ArrayObj_new(hl__types__ArrayObj);
extern hl_type t$_i32;
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);

bool Type_init() {
	bool r1;
	hl_bytes_map *r0, *r2;
	r0 = (hl_bytes_map*)g$__types__;
	if( !r0 ) goto label$9fea9d9_1_4;
	r1 = false;
	return r1;
	label$9fea9d9_1_4:
	r2 = hl_hballoc();
	g$__types__ = (hl_bytes_map*)r2;
	r1 = true;
	return r1;
}

hl__Class Type_initClass(hl_type* r0,hl_type* r1,vbyte* r2) {
	String r8;
	hl__Class r4, r6;
	bool r7;
	vdynamic *r3;
	int r9;
	r3 = hl_type_get_global(r1);
	r4 = (hl__Class)hl_dyn_castp(&r3,&t$_dyn,&t$hl_Class);
	if( !r4 ) goto label$9fea9d9_2_4;
	return r4;
	label$9fea9d9_2_4:
	r3 = hl_alloc_obj(r0);
	r6 = (hl__Class)hl_dyn_castp(&r3,&t$_dyn,&t$hl_Class);
	r7 = hl_type_set_global(r1,((vdynamic*)r6));
	if( r6 == NULL ) hl_null_access();
	r6->_hx___type__ = r1;
	r8 = (String)hl_alloc_obj(&t$String);
	r8->bytes = r2;
	r9 = 0;
	r9 = hl_ucs2length(r2,r9);
	r8->length = r9;
	r6->_hx___name__ = r8;
	Type_register(r2,((hl__BaseType)r6));
	return r6;
}

hl__Enum Type_initEnum(hl_type* r0,hl_type* r1) {
	String r9;
	hl__types__ArrayObj r12;
	bool r16;
	hl_bytes_map *r11;
	hl__Enum r3, r5;
	vdynamic *r2;
	int r10, r13, r14, r15;
	vbyte *r7, *r8;
	varray *r6;
	r2 = hl_type_get_global(r1);
	r3 = (hl__Enum)hl_dyn_castp(&r2,&t$_dyn,&t$hl_Enum);
	if( !r3 ) goto label$9fea9d9_3_4;
	return r3;
	label$9fea9d9_3_4:
	r2 = hl_alloc_obj(r0);
	r5 = (hl__Enum)hl_dyn_castp(&r2,&t$_dyn,&t$hl_Enum);
	r3 = r5;
	if( r5 == NULL ) hl_null_access();
	r5->_hx___type__ = r1;
	r6 = hl_type_enum_values(r1);
	r5->_hx___evalues__ = r6;
	r7 = hl_type_name(r1);
	if( r7 ) goto label$9fea9d9_3_15;
	r9 = NULL;
	goto label$9fea9d9_3_20;
	label$9fea9d9_3_15:
	r9 = (String)hl_alloc_obj(&t$String);
	r9->bytes = r7;
	r10 = 0;
	r10 = hl_ucs2length(r7,r10);
	r9->length = r10;
	label$9fea9d9_3_20:
	r5->_hx___ename__ = r9;
	r11 = hl_hballoc();
	r5->_hx___emap__ = r11;
	r12 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r12);
	r5->_hx___constructs__ = r12;
	r6 = hl_type_enum_fields(r1);
	r10 = 0;
	r13 = r6->size;
	label$9fea9d9_3_29:
	if( r10 >= r13 ) goto label$9fea9d9_3_47;
	r14 = r10;
	++r10;
	r8 = ((vbyte**)(r6 + 1))[r14];
	if( r3 == NULL ) hl_null_access();
	r11 = r3->_hx___emap__;
	r2 = hl_alloc_dynamic(&t$_i32);
	r2->v.i = r14;
	hl_hbset(r11,r8,r2);
	r12 = r3->_hx___constructs__;
	r9 = (String)hl_alloc_obj(&t$String);
	r9->bytes = r8;
	r15 = 0;
	r15 = hl_ucs2length(r8,r15);
	r9->length = r15;
	if( r12 == NULL ) hl_null_access();
	r15 = hl_types_ArrayObj_push(r12,((vdynamic*)r9));
	goto label$9fea9d9_3_29;
	label$9fea9d9_3_47:
	if( r3 == NULL ) hl_null_access();
	r9 = r3->_hx___ename__;
	if( r9 == NULL ) hl_null_access();
	r8 = r9->bytes;
	Type_register(r8,((hl__BaseType)r3));
	r16 = hl_type_set_global(r1,((vdynamic*)r3));
	return r3;
}

void Type_register(vbyte* r0,hl__BaseType r1) {
	hl_bytes_map *r3;
	r3 = (hl_bytes_map*)g$__types__;
	hl_hbset(r3,r0,((vdynamic*)r1));
	return;
}

