// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/iterators/ArrayKeyValueIterator.h>

void haxe_iterators_ArrayKeyValueIterator_new(haxe__iterators__ArrayKeyValueIterator r0,hl__types__ArrayDyn r1) {
	r0->array = r1;
	return;
}

